#!/usr/bin/env node
"use strict";
// Summarizes perf/main/layer_switch_perf.json and perf/tip/layer_switch_perf.json (written by
// tools/test_layer_switch_inplace.js) into perf/summary.md. Usage: node tasks/SIM.00.00/lane-n/perf/summarize.js

const fs = require("fs");
const path = require("path");

const DIR = __dirname;
const load = side => JSON.parse(fs.readFileSync(path.join(DIR, side, "layer_switch_perf.json"), "utf8"));
const sides = { main: load("main"), tip: load("tip") };
const LABEL = { 2: "+2", 1: "+1", 0: "0", "-1": "-1", "-2": "-2" };
const key = s => `${LABEL[s.from]} -> ${LABEL[s.to]}`;
const fmt = v => (typeof v === "number" && Number.isFinite(v) ? (Math.round(v * 10) / 10).toString() : "n/a");
const median = a => { const s = a.slice().sort((x, y) => x - y); return s.length ? s[Math.floor((s.length - 1) / 2)] : NaN; };
const ORDER = ["0 -> +1", "+1 -> +2", "+2 -> 0", "0 -> -1", "-1 -> 0"];

const lines = [];
lines.push("# SIM.00.00 layer switch: main vs lane tip", "");
lines.push(`Generated by \`node tasks/SIM.00.00/lane-n/perf/summarize.js\` from the two \`layer_switch_perf.json\` files. Both were written by`);
lines.push("`node tools/test_layer_switch_inplace.js` (main: `--ref=main`), seed 18, native NW.js (RPG Maker MZ's nw.exe) on this machine,");
lines.push("speed 1x. Bench scenario: from the ground, 0 -> +1 -> +2 -> 0 -> -1 -> 0, rounds 1, 3 and 4 with the fog as in play (disabled);");
lines.push("round 2 is the same sequence with the fog forced on (its numbers are listed apart).", "");
lines.push("Columns: `ms` = UF.Levels.stats().lastSwitch.ms (performance.now from the setView call to the switch's completion: Scene_Map.start on");
lines.push("main, the Spriteset rebind on the tip; it includes the wait for the next frame); `frames` = lastSwitch.frames (Scene_Map updates");
lines.push("between); `worst update` = the slowest SceneManager.updateMain from the request to 2 frames after completion (the hitch a player");
lines.push("sees); `builds` = UF.World.buildArea calls in that window; `skipped` = updateMains in that window that did not advance");
lines.push("UF.Time.ticks() by exactly 1; `new scene` = a Scene_Map was created. `work` (tip only) = swap + rebind + fog refresh, CPU time.", "");
for (const [side, d] of Object.entries(sides)) {
    lines.push(`## ${side}`, "");
    lines.push(`World seed ${d.seed}, ${d.units} units (by level ${JSON.stringify(d.unitsByLevel)}), in-place API ${d.inPlaceApi ? "present" : "absent"}.`);
    if (d.prewarm) lines.push(`Prewarm at the New Game load: ${d.prewarm.builds} builds, ${fmt(d.prewarm.ms)} ms in total (worst ${fmt(d.prewarm.maxMs)} ms), ${d.prewarm.grids} walk grids (${fmt(d.prewarm.gridMs)} ms), ${d.prewarm.loadSteps} load frames held; cold ring levels when the bench started: ${JSON.stringify(d.prewarm.cold)}.`);
    if (d.load) lines.push(`Save/load: the load took ${fmt(d.load.ms)} ms to a started map scene${d.load.diag ? ` (${d.load.diag.builds} level builds during it: ${JSON.stringify(d.load.diag.buildLog)})` : ""}.`);
    lines.push("");
    lines.push("| round | switch | ms | frames | renderFrames | work (swap / rebind / fog) | worst update ms | builds | skipped | new scene |");
    lines.push("|---|---|---|---|---|---|---|---|---|---|");
    for (const s of d.switches) {
        const l = s.last || {};
        const work = l.workMs !== undefined ? `${fmt(l.workMs)} (${fmt(l.swapMs)} / ${fmt(l.rebindMs)} / ${fmt(l.fogMs)})` : "n/a";
        lines.push(`| ${s.round}${s.round === 2 ? " (fog on)" : ""} | ${key(s)} | ${fmt(l.ms)} | ${l.frames !== undefined ? l.frames : "n/a"} | ${l.renderFrames !== undefined ? l.renderFrames : "n/a"} | ${work} | ${fmt(s.maxUpdateMs)} | ${s.builds} | ${s.skipped} | ${s.sameScene ? "no" : "YES"} |`);
    }
    lines.push("");
}
lines.push("## By switch, fog as in play (rounds 1, 3, 4): median / max", "");
lines.push("| switch | main ms | tip ms | main worst update ms | tip worst update ms | main builds | tip builds | main skipped ticks | tip skipped ticks |");
lines.push("|---|---|---|---|---|---|---|---|---|");
for (const k of ORDER) {
    const pick = d => d.switches.filter(s => [1, 3, 4].includes(s.round) && key(s) === k);
    const m = pick(sides.main), t = pick(sides.tip);
    const ms = a => a.map(s => (s.last ? s.last.ms : NaN)).filter(Number.isFinite);
    const up = a => a.map(s => s.maxUpdateMs);
    const sum = (a, f) => a.reduce((n, s) => n + f(s), 0);
    lines.push(`| ${k} | ${fmt(median(ms(m)))} / ${fmt(Math.max(...ms(m)))} | ${fmt(median(ms(t)))} / ${fmt(Math.max(...ms(t)))} | ${fmt(median(up(m)))} / ${fmt(Math.max(...up(m)))} | ${fmt(median(up(t)))} / ${fmt(Math.max(...up(t)))} | ${sum(m, s => s.builds)} | ${sum(t, s => s.builds)} | ${sum(m, s => s.skipped)} | ${sum(t, s => s.skipped)} |`);
}
lines.push("");
lines.push("Limits of these numbers: one run per side on one machine (AMD Ryzen 7 8845HS w/ Radeon 780M, read with Win32_Processor on");
lines.push("2026-09-26), wall-clock performance.now in the game process with other work in the same frames (units walking, AI), no GPU timing.");
lines.push("The first visit of +1, +2 and -1 on main includes the level build; on the tip those builds happened in the load-time prewarm.");
fs.writeFileSync(path.join(DIR, "summary.md"), lines.join("\n") + "\n");
console.log(lines.join("\n"));
