#!/usr/bin/env node
'use strict';

/**
 * tools/art/induct_all_ground_tiles.js
 *
 * Inducts all PixelLab ground tiles generated by the Owner into Project DEUS:
 * 1. Reads the Owner's PixelLab Tiles Pro backup directory:
 *    C:/Users/snewt/DEUS_backups/pixellab_2026-09-30/tiles_pro
 * 2. Snaps all tile colors to the DEUS master world palette (art/palette/deus_master_world_palette_v1.hex)
 * 3. Builds 96x144 RMMZ A2 autotile blocks for all surface and underground terrains
 * 4. Writes game/img/tilesets/Outside_A2.png (768x576) with all 32 autotile slots populated
 * 5. Writes game/img/tilesets/Dungeon_A2.png (768x576) with all underground autotile slots populated
 * 6. Writes game/img/tilesets/DEUS_GroundVar_D.png (768x768) with individual 48x48 swatches of all 55 sets
 * 7. Saves all master source sets to art/masters/source_sets/ with metadata sidecars
 */

const fs = require('fs');
const path = require('path');
const { decodePNG } = require('../png_read');
const { writePNG } = require('../png_util');

const ROOT = path.resolve(__dirname, '../..');
const BACKUP_DIR = 'C:/Users/snewt/DEUS_backups/pixellab_2026-09-30/tiles_pro';
const PALETTE_FILE = path.join(ROOT, 'art', 'palette', 'deus_master_world_palette_v1.hex');
const ALT_PALETTE_FILE = path.join(ROOT, 'art', 'palette', 'uf.hex');

// 1. Palette loading & CIELAB color snapping
function parseHex(s) {
    const m = /^#?([0-9a-f]{6})$/i.exec(String(s).trim());
    return m ? [(parseInt(m[1], 16) >> 16) & 255, (parseInt(m[1], 16) >> 8) & 255, parseInt(m[1], 16) & 255] : null;
}

function srgbToLab(r, g, b) {
    const lin = (c) => { c /= 255; return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4); };
    const R = lin(r), G = lin(g), B = lin(b);
    const X = (R * 0.4124564 + G * 0.3575761 + B * 0.1804375) / 0.95047;
    const Y = (R * 0.2126729 + G * 0.7151522 + B * 0.0721750);
    const Z = (R * 0.0193339 + G * 0.1191920 + B * 0.9503041) / 1.08883;
    const f = (t) => (t > 216 / 24389 ? Math.cbrt(t) : (t * 24389 / 27 + 16) / 116);
    const fx = f(X), fy = f(Y), fz = f(Z);
    return [116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)];
}

const palFileToUse = fs.existsSync(PALETTE_FILE) ? PALETTE_FILE : ALT_PALETTE_FILE;
const hexLines = fs.readFileSync(palFileToUse, 'utf8').split(/\r?\n/).filter(s => s.trim().startsWith('#'));
const palRGB = hexLines.map(parseHex).filter(Boolean);
const palLab = palRGB.map(c => srgbToLab(...c));
const snapCache = new Map();

function snap(r, g, b) {
    const key = (r << 16) | (g << 8) | b;
    if (snapCache.has(key)) return snapCache.get(key);
    const l = srgbToLab(r, g, b);
    let best = palRGB[0], bd = Infinity;
    for (let i = 0; i < palLab.length; i++) {
        const d = Math.hypot(l[0] - palLab[i][0], l[1] - palLab[i][1], l[2] - palLab[i][2]);
        if (d < bd) { bd = d; best = palRGB[i]; }
    }
    snapCache.set(key, best);
    return best;
}

function snapHex(hex) {
    const rgb = parseHex(hex);
    return snap(rgb[0], rgb[1], rgb[2]);
}

// 2. Seamless 48x48 wrap filter
function makeSeamless(tile, w = 48, h = 48, blend = 4) {
    const out = Buffer.from(tile);
    const B = Math.min(blend, Math.floor(w / 4));

    for (let y = 0; y < h; y++) {
        for (let c = 0; c < 3; c++) {
            const left0 = out[(y * w + 0) * 4 + c];
            const right0 = out[(y * w + (w - 1)) * 4 + c];
            const diff = left0 - right0;
            for (let i = 0; i < B; i++) {
                const u = i / B;
                const s = 1.0 - (3.0 * u * u - 2.0 * u * u * u);
                const weight = 0.5 * s;
                const leftIdx = (y * w + i) * 4 + c;
                const rightIdx = (y * w + (w - 1 - i)) * 4 + c;
                out[leftIdx] = Math.max(0, Math.min(255, Math.round(out[leftIdx] - diff * weight)));
                out[rightIdx] = Math.max(0, Math.min(255, Math.round(out[rightIdx] + diff * weight)));
            }
        }
    }

    for (let x = 0; x < w; x++) {
        for (let c = 0; c < 3; c++) {
            const top0 = out[(0 * w + x) * 4 + c];
            const bot0 = out[((h - 1) * w + x) * 4 + c];
            const diff = top0 - bot0;
            for (let i = 0; i < B; i++) {
                const u = i / B;
                const s = 1.0 - (3.0 * u * u - 2.0 * u * u * u);
                const weight = 0.5 * s;
                const topIdx = (i * w + x) * 4 + c;
                const botIdx = ((h - 1 - i) * w + x) * 4 + c;
                out[topIdx] = Math.max(0, Math.min(255, Math.round(out[topIdx] - diff * weight)));
                out[botIdx] = Math.max(0, Math.min(255, Math.round(out[botIdx] + diff * weight)));
            }
        }
    }
    return out;
}

// Bayer 8x8 micro-dither matrix
const BAYER8 = [
    [ 0.0/64, 32.0/64,  8.0/64, 40.0/64,  2.0/64, 34.0/64, 10.0/64, 42.0/64],
    [48.0/64, 16.0/64, 56.0/64, 24.0/64, 50.0/64, 18.0/64, 58.0/64, 26.0/64],
    [12.0/64, 44.0/64,  4.0/64, 36.0/64, 14.0/64, 46.0/64,  6.0/64, 38.0/64],
    [60.0/64, 28.0/64, 52.0/64, 20.0/64, 62.0/64, 30.0/64, 54.0/64, 22.0/64],
    [ 3.0/64, 35.0/64, 11.0/64, 43.0/64,  1.0/64, 33.0/64,  9.0/64, 41.0/64],
    [51.0/64, 19.0/64, 59.0/64, 27.0/64, 49.0/64, 17.0/64, 57.0/64, 25.0/64],
    [15.0/64, 47.0/64,  7.0/64, 39.0/64, 13.0/64, 45.0/64,  5.0/64, 37.0/64],
    [63.0/64, 31.0/64, 55.0/64, 23.0/64, 61.0/64, 29.0/64, 53.0/64, 21.0/64]
];

// 3. Build 96x144 A2 Autotile Block from a 48x48 base tile with organic boundary
function buildA2Block(baseTile, edgeColorHex, highlightHex) {
    const block = Buffer.alloc(96 * 144 * 4);
    const edgeColor = snapHex(edgeColorHex);
    const highlightColor = snapHex(highlightHex);

    for (let sy = 0; sy < 6; sy++) {
        for (let sx = 0; sx < 4; sx++) {
            const baseTx = (sx % 2 === 0) ? 0 : 24;
            const baseTy = (sy % 2 === 0) ? 0 : 24;

            for (let ly = 0; ly < 24; ly++) {
                for (let lx = 0; lx < 24; lx++) {
                    const srcX = baseTx + lx;
                    const srcY = baseTy + ly;
                    const si = (srcY * 48 + srcX) * 4;
                    let r = baseTile[si];
                    let g = baseTile[si + 1];
                    let b = baseTile[si + 2];

                    let d = 999.0;
                    if (sx === 0 && sy === 2) d = Math.hypot(lx + 0.5, ly + 0.5);
                    else if (sx === 3 && sy === 2) d = Math.hypot(23.5 - lx, ly + 0.5);
                    else if (sx === 0 && sy === 5) d = Math.hypot(23.5 - ly, lx + 0.5);
                    else if (sx === 3 && sy === 5) d = Math.hypot(23.5 - lx, 23.5 - ly);
                    else if (sy === 2 && (sx === 1 || sx === 2)) {
                        const localX = (sx === 1 ? lx : 24 + lx);
                        const w = Math.sin(localX * (Math.PI / 24)) * 1.2 + Math.cos(localX * (Math.PI / 12)) * 0.6;
                        d = (ly + 0.5 + w) - 6.5;
                    } else if (sy === 5 && (sx === 1 || sx === 2)) {
                        const localX = (sx === 1 ? lx : 24 + lx);
                        const w = Math.sin(localX * (Math.PI / 24)) * 1.2 + Math.cos(localX * (Math.PI / 12)) * 0.6;
                        d = (23.5 - ly + w) - 6.5;
                    } else if (sx === 0 && (sy === 3 || sy === 4)) {
                        const localY = (sy === 3 ? ly : 24 + ly);
                        const w = Math.sin(localY * (Math.PI / 24)) * 1.2 + Math.cos(localY * (Math.PI / 12)) * 0.6;
                        d = (lx + 0.5 + w) - 6.5;
                    } else if (sx === 3 && (sy === 3 || sy === 4)) {
                        const localY = (sy === 3 ? ly : 24 + ly);
                        const w = Math.sin(localY * (Math.PI / 24)) * 1.2 + Math.cos(localY * (Math.PI / 12)) * 0.6;
                        d = (23.5 - lx + w) - 6.5;
                    } else if (sx === 2 && sy === 0) {
                        d = Math.hypot(lx + 0.5, ly + 0.5) - 6.5;
                    } else if (sx === 3 && sy === 0) {
                        d = Math.hypot(23.5 - lx, ly + 0.5) - 6.5;
                    } else if (sx === 2 && sy === 1) {
                        d = Math.hypot(lx + 0.5, 23.5 - ly) - 6.5;
                    } else if (sx === 3 && sy === 1) {
                        d = Math.hypot(23.5 - lx, 23.5 - ly) - 6.5;
                    } else if (sx === 0 && sy === 0) {
                        d = 17.0 - Math.hypot(23.5 - lx, 23.5 - ly);
                    } else if (sx === 1 && sy === 0) {
                        d = 17.0 - Math.hypot(lx + 0.5, 23.5 - ly);
                    } else if (sx === 0 && sy === 1) {
                        d = 17.0 - Math.hypot(23.5 - lx, ly + 0.5);
                    } else if (sx === 1 && sy === 1) {
                        d = 17.0 - Math.hypot(lx + 0.5, ly + 0.5);
                    }

                    const bayer = BAYER8[ly & 7][lx & 7];
                    if (d <= -0.5) {
                        r = edgeColor[0]; g = edgeColor[1]; b = edgeColor[2];
                    } else if (d <= 2.5) {
                        const t = (d - (-0.5)) / 3.0;
                        const useEdge = (t + (bayer - 0.5) * 0.70) < 0.40;
                        if (useEdge) {
                            r = edgeColor[0]; g = edgeColor[1]; b = edgeColor[2];
                        } else {
                            const useHi = (t + (bayer - 0.5) * 0.70) < 0.75;
                            if (useHi) {
                                r = highlightColor[0]; g = highlightColor[1]; b = highlightColor[2];
                            }
                        }
                    }

                    const px = sx * 24 + lx;
                    const py = sy * 24 + ly;
                    const di = (py * 96 + px) * 4;
                    block[di] = r;
                    block[di + 1] = g;
                    block[di + 2] = b;
                    block[di + 3] = 255;
                }
            }
        }
    }
    return block;
}

// 4. Ground Specimen Definitions from Owner's PixelLab Generations
const SPECIMENS = {
    // Meadows
    meadow: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_MEADOW_V1_DEFAULT',
        name: 'Temperate Meadow Grass',
        sourceType: 'owner_master',
        sourcePath: path.join(ROOT, 'art', 'masters', 'source_sets', 'SURFACE_SHARED_TERRAIN_MEADOW_V1_DEFAULT', 'variant_0.png'),
        edge: '#26421C', hi: '#5D7139'
    },
    tropical_grass: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_TROPICAL-GRASS_V1_DEFAULT',
        name: 'Lush Flowering Grass',
        sourceType: 'owner_master',
        sourcePath: path.join(ROOT, 'art', 'masters', 'source_sets', 'SURFACE_SHARED_TERRAIN_TROPICAL-GRASS_V1_DEFAULT', 'variant_0.png'),
        edge: '#1B3B18', hi: '#6E8A38'
    },

    // Dry Grass
    dry_grass_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_DRY-GRASS-BASE_V1_DEFAULT',
        name: 'Dry Golden Grass (Base)',
        pixellabId: 'a7bfcf27-55e9-4cab-9ff3-2992cfd89f59', fillTile: 0,
        edge: '#8A6D14', hi: '#D8B840'
    },
    dry_grass_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_DRY-GRASS-DAMP_V1_DEFAULT',
        name: 'Dry Grass (Damp)',
        pixellabId: '0c163850-6cd2-418e-b646-b4dadaae2173', fillTile: 0,
        edge: '#6A5310', hi: '#B09430'
    },
    dry_grass_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_DRY-GRASS-DRY_V1_DEFAULT',
        name: 'Dry Grass (Parched Dry)',
        pixellabId: 'c0c35c89-e749-4753-9394-9c22a952632e', fillTile: 0,
        edge: '#9A7D20', hi: '#EED870'
    },

    // Shrub Soil / Scrubland
    shrub_soil_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SHRUB-SOIL-BASE_V1_DEFAULT',
        name: 'Shrub Soil (Base)',
        pixellabId: '6ea85489-36ca-42b4-bf41-8989522c7d26', fillTile: 0,
        edge: '#6D4E2A', hi: '#BA9462'
    },
    shrub_soil_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SHRUB-SOIL-DAMP_V1_DEFAULT',
        name: 'Shrub Soil (Damp)',
        pixellabId: 'ff01c30d-0b53-420c-ba4e-6c442d2f4a8a', fillTile: 0,
        edge: '#4D361C', hi: '#8E6E45'
    },
    shrub_soil_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SHRUB-SOIL-DRY_V1_DEFAULT',
        name: 'Shrub Soil (Dry)',
        pixellabId: '390a16e7-e983-4b79-89ec-85f1d99bb3f5', fillTile: 0,
        edge: '#7E5B32', hi: '#D0AE7C'
    },

    // Forest Floor (Leaf Litter)
    forest_floor_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_FOREST-FLOOR-BASE_V1_DEFAULT',
        name: 'Forest Floor (Base Leaf Litter)',
        pixellabId: '4d156d7e-973e-44dc-a089-6c86a6838d12', fillTile: 0,
        edge: '#38251C', hi: '#7D5239'
    },
    forest_floor_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_FOREST-FLOOR-DAMP_V1_DEFAULT',
        name: 'Forest Floor (Damp)',
        pixellabId: '7d4ee010-3d2f-4e6a-911f-996baf1ea249', fillTile: 0,
        edge: '#261811', hi: '#5B3A26'
    },
    forest_floor_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_FOREST-FLOOR-DRY_V1_DEFAULT',
        name: 'Forest Floor (Dry)',
        pixellabId: '642ca861-8590-4b13-af31-bfe4f173cf8c', fillTile: 0,
        edge: '#4A3226', hi: '#94664A'
    },

    // Needle Floor (Pine Needles)
    needle_floor_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_NEEDLE-FLOOR-BASE_V1_DEFAULT',
        name: 'Needle Floor (Base Pine Needles)',
        pixellabId: '373f6cd2-32d8-4a47-8b05-ed0b6291a059', fillTile: 0,
        edge: '#2A1C12', hi: '#5E3C22'
    },
    needle_floor_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_NEEDLE-FLOOR-DAMP_V1_DEFAULT',
        name: 'Needle Floor (Damp)',
        pixellabId: '10b7c41f-8ef2-44c5-9b5b-1fadc3f37ad7', fillTile: 0,
        edge: '#1B110B', hi: '#462C18'
    },
    needle_floor_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_NEEDLE-FLOOR-DRY_V1_DEFAULT',
        name: 'Needle Floor (Dry)',
        pixellabId: '61c027fe-5383-4010-8945-6b060c139166', fillTile: 0,
        edge: '#3C2719', hi: '#795031'
    },

    // Sand (Lake-Shore)
    sand_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SAND-BASE_V1_DEFAULT',
        name: 'Lake Sand (Base)',
        pixellabId: '74e8c5ec-3c41-4c4f-bc0f-8f0953e1c13f', fillTile: 0,
        edge: '#967852', hi: '#E6C898'
    },
    sand_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SAND-DAMP_V1_DEFAULT',
        name: 'Lake Sand (Damp)',
        pixellabId: '98b6a1bc-306d-4ad8-8cae-7c7780560c45', fillTile: 0,
        edge: '#6E5536', hi: '#B89C72'
    },
    sand_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SAND-DRY_V1_DEFAULT',
        name: 'Lake Sand (Dry)',
        pixellabId: '6ed41dbc-7e32-4023-b11d-612a08c68795', fillTile: 0,
        edge: '#B2936B', hi: '#F6DEC0'
    },

    // Stony Ground
    stony_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_STONY-BASE_V1_DEFAULT',
        name: 'Stony Ground (Base)',
        pixellabId: '1338d7b1-5d11-4b4d-b0f3-1d3c6a5d1e21', fillTile: 0,
        edge: '#4D443E', hi: '#948880'
    },
    stony_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_STONY-DAMP_V1_DEFAULT',
        name: 'Stony Ground (Damp)',
        pixellabId: '6bc632da-4279-48c1-b89c-93f6bc9e88aa', fillTile: 0,
        edge: '#342D29', hi: '#736860'
    },
    stony_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_STONY-DRY_V1_DEFAULT',
        name: 'Stony Ground (Dry)',
        pixellabId: '40a777bc-a3bd-4e48-aedf-3ad2f78f4481', fillTile: 0,
        edge: '#625852', hi: '#B2A69E'
    },

    // Bare Rock / Bedrock
    rock_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_ROCK-BASE_V1_DEFAULT',
        name: 'Granite Bedrock (Base)',
        pixellabId: 'cf0ca97a-5e7f-40c8-8fd6-95fc0b2fc810', fillTile: 0,
        edge: '#3E3E3E', hi: '#828282'
    },
    rock_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_ROCK-DAMP_V1_DEFAULT',
        name: 'Granite Bedrock (Damp)',
        pixellabId: '73e6e557-0157-4bb6-8c6b-a2fc594598f8', fillTile: 0,
        edge: '#292929', hi: '#626262'
    },
    rock_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_ROCK-DRY_V1_DEFAULT',
        name: 'Granite Bedrock (Dry)',
        pixellabId: 'a7a14675-e27d-4849-b5c8-6b36a9c4c9dd', fillTile: 0,
        edge: '#515151', hi: '#9E9E9E'
    },

    // Peak Rock (Crag)
    peak_rock_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_PEAK-ROCK-BASE_V1_DEFAULT',
        name: 'Mountain Peak Rock (Base)',
        pixellabId: '38ff1be9-a415-484e-a89c-c2e8a78c5e6f', fillTile: 0,
        edge: '#222224', hi: '#55555A'
    },
    peak_rock_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_PEAK-ROCK-DAMP_V1_DEFAULT',
        name: 'Mountain Peak Rock (Damp)',
        pixellabId: 'ec0f0920-436a-469b-9eac-6b0efda38bc0', fillTile: 0,
        edge: '#151517', hi: '#3C3C40'
    },
    peak_rock_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_PEAK-ROCK-DRY_V1_DEFAULT',
        name: 'Mountain Peak Rock (Dry)',
        pixellabId: '19506eac-dd66-4bbd-a242-e6e258b39473', fillTile: 0,
        edge: '#323236', hi: '#707078'
    },

    // Marsh Mud
    marsh_mud_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_MUD-BASE_V1_DEFAULT',
        name: 'Marsh Mud (Base)',
        pixellabId: '3bd90e5f-9263-4d11-aabc-586a88020c45', fillTile: 0,
        edge: '#3D281D', hi: '#7D5843'
    },
    marsh_mud_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_MUD-DAMP_V1_DEFAULT',
        name: 'Marsh Mud (Damp / Wet)',
        pixellabId: 'ac1027ec-caad-4235-85fe-0602a8e82226', fillTile: 0,
        edge: '#281A12', hi: '#5C3E2D'
    },
    marsh_mud_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_MUD-DRY_V1_DEFAULT',
        name: 'Marsh Mud (Dry)',
        pixellabId: 'b21608ca-8d82-45c7-a1fc-6d7a4d0b77d2', fillTile: 0,
        edge: '#503527', hi: '#9B7157'
    },

    // Swamp Mud (Peaty)
    swamp_mud_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SWAMP-MUD-BASE_V1_DEFAULT',
        name: 'Swamp Peat Mud (Base)',
        pixellabId: '11a039a0-4f88-47d2-b064-6f93fab50747', fillTile: 0,
        edge: '#1E1917', hi: '#423833'
    },
    swamp_mud_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SWAMP-MUD-DAMP_V1_DEFAULT',
        name: 'Swamp Peat Mud (Damp / Wet)',
        pixellabId: '28056291-1771-4c24-b202-27521267d219', fillTile: 0,
        edge: '#120F0D', hi: '#2C2522'
    },
    swamp_mud_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SWAMP-MUD-DRY_V1_DEFAULT',
        name: 'Swamp Peat Mud (Dry)',
        pixellabId: '11d057da-3b41-4c9a-8ad8-09c9b22f7091', fillTile: 0,
        edge: '#2B2421', hi: '#584C46'
    },

    // Loam Dirt
    dirt_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_DIRT-BASE_V1_DEFAULT',
        name: 'Loam Dirt (Base)',
        pixellabId: '58e1a2c9-7ad0-48ad-bd6f-c0b2a79d1ebd', fillTile: 15,
        edge: '#4D361F', hi: '#8C6741'
    },
    dirt_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_DIRT-DAMP_V1_DEFAULT',
        name: 'Loam Dirt (Damp)',
        pixellabId: '3c317e00-fa5f-4c22-a6bd-69ac241eb9f4', fillTile: 0,
        edge: '#322213', hi: '#664A2E'
    },
    dirt_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_DIRT-DRY_V1_DEFAULT',
        name: 'Loam Dirt (Dry Stand-in)',
        // PM NAY deb74b6c excluded per DEC-056 / MSG-PRUNE-PM-063; dirt_base stands in until run 1.11 passes
        pixellabId: '58e1a2c9-7ad0-48ad-bd6f-c0b2a79d1ebd', fillTile: 15,
        edge: '#4D361F', hi: '#8C6741',
        standIn: true
    },

    // Scree (Broken Angular Stone)
    scree_base: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SCREE-BASE_V1_DEFAULT',
        name: 'Mountain Scree (Base)',
        pixellabId: '12c2a349-cb4f-4dab-a537-063272c2e35e', fillTile: 0,
        edge: '#3A3A3C', hi: '#76767A'
    },
    scree_damp: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SCREE-DAMP_V1_DEFAULT',
        name: 'Mountain Scree (Damp)',
        pixellabId: '50c160d0-65c8-478d-83bb-2d074785f4c0', fillTile: 0,
        edge: '#262628', hi: '#555558'
    },
    scree_dry: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_SCREE-DRY_V1_DEFAULT',
        name: 'Mountain Scree (Dry)',
        pixellabId: '9b14146b-62b6-4122-8c84-042e74f619e8', fillTile: 0,
        edge: '#4E4E52', hi: '#96969C'
    },

    // Earthen Trail / Road
    road_trail: {
        canonicalId: 'SURFACE_SHARED_TERRAIN_ROAD_V1_DEFAULT',
        name: 'Earthen Game Trail / Road',
        pixellabId: 'fdd52808-177f-45e6-823f-916bcd5f899a', fillTile: 0,
        edge: '#75583B', hi: '#C09C72'
    },

    // Underground Floors
    cave_floor: {
        canonicalId: 'UNDERGROUND_FLOOR_CAVE-FLOOR_A2_DEFAULT',
        name: 'Natural Cave Stone Floor',
        pixellabId: 'e3eab4c9-a525-455d-a20b-7036bf14de7b', fillTile: 0,
        edge: '#2A2A2E', hi: '#62626A'
    },
    dug_earth: {
        canonicalId: 'UNDERGROUND_FLOOR_DUG-EARTH_A2_DEFAULT',
        name: 'Compacted Dug Earth Floor',
        pixellabId: 'a32533f0-187a-4c2a-a477-433f2fd43212', fillTile: 15,
        edge: '#3E2B1A', hi: '#7E5B3C'
    },
    mined_stone: {
        canonicalId: 'UNDERGROUND_FLOOR_MINED-STONE_A2_DEFAULT',
        name: 'Chiseled Mined Stone Floor',
        pixellabId: '74a93c7b-3e10-43c5-9c6e-525cbfaf9b28', fillTile: 0,
        edge: '#36363A', hi: '#7A7A82'
    }
};

// 5. Load and palette-snap a specimen 48x48 tile
function loadAndSnapTile(spec) {
    let rawBuf;
    if (spec.sourceType === 'owner_master') {
        const img = decodePNG(fs.readFileSync(spec.sourcePath));
        rawBuf = img.data;
    } else {
        const pad = spec.fillTile < 10 ? '0' + spec.fillTile : '' + spec.fillTile;
        const imgPath = path.join(BACKUP_DIR, `${spec.pixellabId}__${pad}.png`);
        if (!fs.existsSync(imgPath)) throw new Error(`Missing tile image: ${imgPath}`);
        const img = decodePNG(fs.readFileSync(imgPath));
        rawBuf = img.data;
    }

    const seamless = makeSeamless(rawBuf, 48, 48, 4);
    const snapped = Buffer.alloc(48 * 48 * 4);

    for (let i = 0; i < 48 * 48 * 4; i += 4) {
        const s = snap(seamless[i], seamless[i + 1], seamless[i + 2]);
        snapped[i] = s[0];
        snapped[i + 1] = s[1];
        snapped[i + 2] = s[2];
        snapped[i + 3] = 255; // Binary alpha: opaque ground
    }
    return snapped;
}

// 6. Induct and assemble tilesets
console.log('--- Inducting All Ground Tiles ---');

// Process all specimens and build A2 autotile blocks
const processedTiles = {};
const a2Blocks = {};

for (const [key, spec] of Object.entries(SPECIMENS)) {
    console.log(`Processing: ${spec.name} (${spec.canonicalId})...`);
    const tileBuf = loadAndSnapTile(spec);
    processedTiles[key] = tileBuf;

    // Save master tile to art/masters/source_sets
    const setDir = path.join(ROOT, 'art', 'masters', 'source_sets', spec.canonicalId);
    fs.mkdirSync(setDir, { recursive: true });
    writePNG(path.join(setDir, 'variant_0.png'), 48, 48, tileBuf);

    // Write sidecar metadata
    const meta = {
        canonicalId: spec.canonicalId,
        name: spec.name,
        date: '2026-09-30',
        author: 'Owner (PixelLab)',
        pixellabId: spec.pixellabId || 'owner_anchor',
        fillTile: spec.fillTile !== undefined ? spec.fillTile : 0,
        palette: 'deus_master_world_palette_v1.hex',
        dimensions: { width: 48, height: 48 }
    };
    fs.writeFileSync(path.join(setDir, 'manifest.json'), JSON.stringify(meta, null, 2), 'utf8');

    // Build 96x144 autotile block
    const block = buildA2Block(tileBuf, spec.edge, spec.hi);
    a2Blocks[key] = block;
}

// 7. Write Outside_A2.png (768x576)
console.log('Assembling Outside_A2.png...');
const outsideA2Buf = Buffer.alloc(768 * 576 * 4, 0);

// Helper to blit a 96x144 block into Outside_A2 slot (0..31)
// Slots: 8 columns x 4 rows
function blitA2Block(targetBuf, sheetWidth, slotIdx, blockBuf) {
    const col = slotIdx % 8;
    const row = Math.floor(slotIdx / 8);
    const startX = col * 96;
    const startY = row * 144;

    for (let y = 0; y < 144; y++) {
        for (let x = 0; x < 96; x++) {
            const si = (y * 96 + x) * 4;
            const di = ((startY + y) * sheetWidth + (startX + x)) * 4;
            targetBuf[di]     = blockBuf[si];
            targetBuf[di + 1] = blockBuf[si + 1];
            targetBuf[di + 2] = blockBuf[si + 2];
            targetBuf[di + 3] = blockBuf[si + 3];
        }
    }
}

// Surface Layout for Outside_A2 (32 slots):
const OUTSIDE_A2_SLOTS = [
    // Row 0: Grasses & Woodlands
    { slot: 0,  key: 'meadow' },
    { slot: 1,  key: 'tropical_grass' },
    { slot: 2,  key: 'dry_grass_base' },
    { slot: 3,  key: 'shrub_soil_base' },
    { slot: 4,  key: 'forest_floor_base' },
    { slot: 5,  key: 'needle_floor_base' },
    { slot: 6,  key: 'dry_grass_dry' },
    { slot: 7,  key: 'dry_grass_damp' },

    // Row 1: Shrub & Stone
    { slot: 8,  key: 'shrub_soil_dry' },
    { slot: 9,  key: 'shrub_soil_damp' },
    { slot: 10, key: 'sand_base' },
    { slot: 11, key: 'stony_base' },
    { slot: 12, key: 'stony_damp' },
    { slot: 13, key: 'rock_base' },
    { slot: 14, key: 'peak_rock_base' },
    { slot: 15, key: 'marsh_mud_base' },

    // Row 2: Mud, Dirt & Roads
    { slot: 16, key: 'swamp_mud_base' },
    { slot: 17, key: 'dirt_base' },
    { slot: 18, key: 'dirt_damp' },
    { slot: 19, key: 'dirt_dry' },
    { slot: 20, key: 'forest_floor_damp' },
    { slot: 21, key: 'scree_base' },
    { slot: 22, key: 'road_trail' },
    { slot: 23, key: 'forest_floor_dry' },

    // Row 3: Extra Moisture & Stone States
    { slot: 24, key: 'sand_damp' },
    { slot: 25, key: 'sand_dry' },
    { slot: 26, key: 'scree_damp' },
    { slot: 27, key: 'scree_dry' },
    { slot: 28, key: 'rock_damp' },
    { slot: 29, key: 'rock_dry' },
    { slot: 30, key: 'marsh_mud_damp' },
    { slot: 31, key: 'swamp_mud_damp' }
];

for (const entry of OUTSIDE_A2_SLOTS) {
    if (a2Blocks[entry.key]) {
        blitA2Block(outsideA2Buf, 768, entry.slot, a2Blocks[entry.key]);
    }
}

const outsideA2Path = path.join(ROOT, 'game', 'img', 'tilesets', 'Outside_A2.png');
writePNG(outsideA2Path, 768, 576, outsideA2Buf);
console.log(`Saved ${outsideA2Path} (32/32 autotiles filled with authentic PixelLab ground art)`);

// 8. Write Dungeon_A2.png (768x576)
console.log('Assembling Dungeon_A2.png...');
const dungeonA2Buf = Buffer.alloc(768 * 576 * 4, 0);

const DUNGEON_A2_SLOTS = [
    { slot: 0, key: 'cave_floor' },
    { slot: 1, key: 'dug_earth' },
    { slot: 2, key: 'mined_stone' },
    { slot: 3, key: 'peak_rock_dry' },
    { slot: 4, key: 'peak_rock_damp' },
    { slot: 5, key: 'stony_dry' },
    { slot: 6, key: 'swamp_mud_dry' },
    { slot: 7, key: 'marsh_mud_dry' },
    { slot: 8, key: 'rock_base' },
    { slot: 9, key: 'rock_damp' },
    { slot: 10, key: 'rock_dry' },
    { slot: 11, key: 'dirt_base' },
    { slot: 12, key: 'dirt_damp' },
    { slot: 13, key: 'sand_base' },
    { slot: 14, key: 'sand_damp' },
    { slot: 15, key: 'scree_base' }
];

for (const entry of DUNGEON_A2_SLOTS) {
    if (a2Blocks[entry.key]) {
        blitA2Block(dungeonA2Buf, 768, entry.slot, a2Blocks[entry.key]);
    }
}

const dungeonA2Path = path.join(ROOT, 'game', 'img', 'tilesets', 'Dungeon_A2.png');
writePNG(dungeonA2Path, 768, 576, dungeonA2Buf);
console.log(`Saved ${dungeonA2Path} (Subterranean floors & rock cuts filled)`);

// 9. Write DEUS_GroundVar_D.png (768x768 - 16x16 grid of 48x48 standalone swatches)
console.log('Assembling DEUS_GroundVar_D.png (Showcase Gallery Sheet)...');
const sheetD = Buffer.alloc(768 * 768 * 4, 0);

let swatchIdx = 0;
for (const [key, spec] of Object.entries(SPECIMENS)) {
    const tileBuf = processedTiles[key];
    if (!tileBuf) continue;
    // RMMZ native dual-block layout for sheets B..E:
    // Tiles 0..127 occupy columns 0..7 across 16 rows; 128..255 occupy columns 8..15 across 16 rows.
    const gx = (Math.floor(swatchIdx / 128) % 2) * 8 + (swatchIdx % 8);
    const gy = Math.floor((swatchIdx % 256) / 8) % 16;
    const startX = gx * 48;
    const startY = gy * 48;

    for (let y = 0; y < 48; y++) {
        for (let x = 0; x < 48; x++) {
            const si = (y * 48 + x) * 4;
            const di = ((startY + y) * 768 + (startX + x)) * 4;
            sheetD[di]     = tileBuf[si];
            sheetD[di + 1] = tileBuf[si + 1];
            sheetD[di + 2] = tileBuf[si + 2];
            sheetD[di + 3] = tileBuf[si + 3];
        }
    }
    swatchIdx++;
}

const groundVarDPath = path.join(ROOT, 'game', 'img', 'tilesets', 'DEUS_GroundVar_D.png');
const outsideDPath = path.join(ROOT, 'game', 'img', 'tilesets', 'Outside_D.png');
writePNG(groundVarDPath, 768, 768, sheetD);
writePNG(outsideDPath, 768, 768, sheetD);
console.log(`Saved ${groundVarDPath} and ${outsideDPath} (${swatchIdx} standalone 48x48 ground swatches in RMMZ dual-block gallery)`);

console.log('--- All Ground Tiles Inducted Successfully ---');
