#!/usr/bin/env node
"use strict";
// OPS.30.01 lane-y: builds the census tables of REPORT.md from the committed evidence (no suite is run).
// Usage: node tasks/OPS.30.01/lane-y/analysis/report_tables.js > tasks/OPS.30.01/lane-y/census_tables.md
// Inputs: evidence/census_run{1,2,3}.json, evidence/census_tip_run{1,2,3}.json, tools/ops/quarantine.json,
// tools/ops/gate_tests.json, evidence/classify_tests_output_at_425b594c.md (tools/classify_tests.js run at the base).
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..", "..", "..", "..");
const EV = path.join(__dirname, "..", "evidence");
const read = f => JSON.parse(fs.readFileSync(f, "utf8"));
const runs = [1, 2, 3].map(k => read(path.join(EV, `census_run${k}.json`)));
const tip = [1, 2, 3].map(k => read(path.join(EV, `census_tip_run${k}.json`)));
const q = read(path.join(ROOT, "tools", "ops", "quarantine.json"));
const gt = read(path.join(ROOT, "tools", "ops", "gate_tests.json"));
const CATS = ["PASS", "FAIL_MISSING_DEPENDENCY", "FAIL_API_DRIFT", "FAIL_MISSING_REFERENCE", "FAIL_OTHER", "KILLED_TIMEOUT", "NEEDS_NWJS"];
const cell = s => String(s == null ? "" : s).replace(/\|/g, "\\|").replace(/`/g, "'");
const cut = (s, n) => { s = String(s == null ? "" : s); return s.length > n ? `${s.slice(0, n - 3)}...` : s; };

// Per-suite runs.
const per = new Map();
for (const set of [runs, tip]) set.forEach((r, i) => r.suites.forEach(s => {
    if (!per.has(s.path)) per.set(s.path, []);
    per.get(s.path)[i] = s;
}));
const gateSet = new Set(gt.gate);
const qMap = new Map(q.suites.map(s => [s.path, s]));
const pMap = new Map(q.passingNotGated.map(s => [s.path, s]));
const listOf = p => (gateSet.has(p) ? "gate" : qMap.has(p) ? "quarantine" : pMap.has(p) ? "passingNotGated" : "(none)");
const finalCat = p => (qMap.has(p) ? qMap.get(p).category + (qMap.get(p).flaky ? " (flaky)" : "") : pMap.has(p) ? "PASS" : null);
const out = [];
const w = s => out.push(s);

w("<!-- generated by tasks/OPS.30.01/lane-y/analysis/report_tables.js from the committed evidence; do not edit by hand -->");
w("");
w("### Counts per category");
w("");
w("Census of `425b594c` (3 runs, fresh clone each, timeout 180 s, 3 at once) plus `tools/ops/test_run_gate.js` (added by this lane, 3 runs on lane commit `" + tip[0].head.slice(0, 8) + "`).");
w("");
w("| Category | run 1 | run 2 | run 3 | quarantine.json (non-gate, 3/3 rule) |");
w("|---|---|---|---|---|");
const final = {};
for (const c of CATS) final[c] = 0;
for (const s of q.suites) final[s.category]++;
final.PASS = q.passingNotGated.length;
for (const c of CATS) {
    const n = runs.map(r => r.suites.filter(s => s.category === c).length);
    w(`| ${c} | ${n.join(" | ")} | ${c === "PASS" ? `${final.PASS} passingNotGated` : final[c]} |`);
}
w(`| total | ${runs.map(r => r.suites.length).join(" | ")} | ${q.suites.length + q.passingNotGated.length} non-gate + ${gt.gate.length} gate = ${q.suites.length + q.passingNotGated.length + gt.gate.length} |`);
w("");
w("Run columns count all 188 suites of the base, gate suites included; the last column leaves out the 9 gate suites and adds `tools/ops/test_run_gate.js`.");
w("");

// Agreement.
const disagree = [...per.entries()].filter(([, rs]) => new Set(rs.map(x => x.category)).size > 1);
w("### Agreement across the three runs");
w("");
w(`${per.size - disagree.length} of ${per.size} suites got the same category in all three runs; ${disagree.length} did not:`);
w("");
w("| Suite | list | run 1 | run 2 | run 3 | ms (runs) |");
w("|---|---|---|---|---|---|");
for (const [p, rs] of disagree) w(`| \`${p}\` | ${listOf(p)} | ${rs.map(x => x.category).join(" | ")} | ${rs.map(x => x.ms).join(" / ")} |`);
w("");
const lineDiff = [...per.entries()].filter(([, rs]) => new Set(rs.map(x => x.category)).size === 1 && new Set(rs.map(x => x.firstErrorLine)).size > 1);
w(`Suites with the same category but a different deciding line between runs: ${lineDiff.length}${lineDiff.length ? ` (${lineDiff.map(([p]) => `\`${p}\``).join(", ")})` : ""}.`);
w("");

// Gate suites.
w("### Gate suites in the census (timeout 180 s, 3 at once)");
w("");
w("| Gate suite | run 1 | run 2 | run 3 | ms (runs) |");
w("|---|---|---|---|---|");
for (const g of gt.gate) { const rs = per.get(g) || []; w(`| \`${g}\` | ${rs.map(x => x.category).join(" | ")} | ${rs.map(x => x.ms).join(" / ")} |`); }
w("");

// Full list.
w("### Every suite");
w("");
w("`list` is where the suite is now: the gate list (gate_tests.json, read only), the quarantine (`quarantine.json` suites) or `passingNotGated`. `ms` is the longest of the three runs. The deciding line is cut at 150 characters; the full line is in quarantine.json and the census files.");
w("");
w("| # | Suite | list | category | runs | ms | deciding line |");
w("|---|---|---|---|---|---|---|");
let n = 0;
for (const p of [...per.keys()].sort()) {
    const rs = per.get(p);
    const cats = rs.map(x => x.category);
    const same = new Set(cats).size === 1;
    const ms = rs.map(x => x.ms).filter(v => typeof v === "number");
    const cat = gateSet.has(p) ? (same ? cats[0] : "(gate, see above)") : finalCat(p);
    const line = qMap.has(p) ? qMap.get(p).firstErrorLine : (rs.find(x => x.firstErrorLine) || {}).firstErrorLine || "";
    w(`| ${++n} | \`${p}\` | ${listOf(p)} | ${cat} | ${same ? "3/3" : cats.map(c => c.replace(/^FAIL_|_TIMEOUT$/g, "")).join("/")} | ${ms.length ? Math.max(...ms) : "-"} | ${cell(cut(line, 150))} |`);
}
w("");

// classify_tests.js comparison.
const md = fs.readFileSync(path.join(EV, "classify_tests_output_at_425b594c.md"), "utf8");
const heur = new Map();
let sec = null;
for (const l of md.split(/\r?\n/)) {
    const h = /^### (\w+) \(\d+\)/.exec(l);
    if (h) { sec = h[1]; continue; }
    const r = /^\| `([^`]+)` \|/.exec(l);
    if (r && sec) heur.set(`tools/${r[1]}`, sec);
}
const measured = p => {
    const rs = per.get(p);
    const cats = rs.map(x => x.category);
    return new Set(cats).size === 1 ? cats[0] : "FLAKY";
};
const HEUR = ["HEADLESS_AUTOMATED", "PLAYTEST_IN_GAME", "ART_PIPELINE", "UTILITY_TOOL", "LEGACY_OR_STALE", "(not seen)"];
const MEAS = ["PASS", "FAIL_API_DRIFT", "FAIL_MISSING_REFERENCE", "FAIL_OTHER", "KILLED_TIMEOUT", "FLAKY", "NEEDS_NWJS"];
const tab = {};
for (const h of HEUR) { tab[h] = {}; for (const m of MEAS) tab[h][m] = []; }
for (const p of per.keys()) {
    const h = heur.get(p) || "(not seen)";
    tab[h][measured(p)].push(p);
}
w("### tools/classify_tests.js heuristic against the measurement");
w("");
w(`\`tools/classify_tests.js\`, run at \`425b594c\` in a throwaway clone (evidence/classify_tests_run.log, output evidence/classify_tests_output_at_425b594c.md), labels ${heur.size} top-level \`tools/*.js\` files. It does not look into subfolders, so the nested suites are "(not seen)". Rows: the heuristic's label; columns: the measured category (FLAKY = the runs disagreed).`);
w("");
w(`| heuristic \\ measured | ${MEAS.join(" | ")} | total |`);
w(`|---|${MEAS.map(() => "---").join("|")}|---|`);
for (const h of HEUR) {
    const row = MEAS.map(m => tab[h][m].length);
    const t = row.reduce((a, b) => a + b, 0);
    if (t) w(`| ${h} | ${row.join(" | ")} | ${t} |`);
}
w("");
const headlessBad = MEAS.filter(m => m !== "PASS").reduce((a, m) => a + tab.HEADLESS_AUTOMATED[m].length, 0);
const playBad = MEAS.filter(m => m !== "NEEDS_NWJS").reduce((a, m) => a + tab.PLAYTEST_IN_GAME[m].length, 0);
const nwNotPlay = HEUR.filter(h => h !== "PLAYTEST_IN_GAME").reduce((a, h) => a + tab[h].NEEDS_NWJS.length, 0);
const nonSuite = ["ART_PIPELINE", "UTILITY_TOOL", "LEGACY_OR_STALE"].reduce((a, h) => a + MEAS.reduce((b, m) => b + tab[h][m].length, 0), 0);
w(`- Labelled HEADLESS_AUTOMATED ("runnable in CI") but not passing: **${headlessBad}** of ${MEAS.reduce((a, m) => a + tab.HEADLESS_AUTOMATED[m].length, 0)}.`);
w(`- Labelled PLAYTEST_IN_GAME ("requires live RMMZ") but not NEEDS_NWJS: **${playBad}** of ${MEAS.reduce((a, m) => a + tab.PLAYTEST_IN_GAME[m].length, 0)}.`);
w(`- Mislabelled on runnability (the two lines above): **${headlessBad + playBad}**.`);
w(`- NEEDS_NWJS suites the heuristic did not label PLAYTEST_IN_GAME: ${nwNotPlay} (${HEUR.filter(h => h !== "PLAYTEST_IN_GAME" && tab[h].NEEDS_NWJS.length).map(h => `${h} ${tab[h].NEEDS_NWJS.length}`).join(", ")}).`);
w(`- Suites (tracked \`test_*.js\`) the heuristic files as a non-test (ART_PIPELINE, UTILITY_TOOL, LEGACY_OR_STALE): ${nonSuite}; not seen at all: ${MEAS.reduce((a, m) => a + tab["(not seen)"][m].length, 0)}.`);
w("");
w("Mislabelled PLAYTEST_IN_GAME suites (measured, not NEEDS_NWJS):");
w("");
for (const m of MEAS.filter(x => x !== "NEEDS_NWJS")) for (const p of tab.PLAYTEST_IN_GAME[m]) w(`- \`${p}\`: ${m}`);
w("");
w("NEEDS_NWJS suites labelled HEADLESS_AUTOMATED:");
w("");
for (const p of tab.HEADLESS_AUTOMATED.NEEDS_NWJS) w(`- \`${p}\``);
w("");
process.stdout.write(out.join("\n") + "\n");
