// Registers UF_Test in a plugins.js file (used for disposable test copies of the game).
// Usage: node tools/add_test_plugin.js <path to plugins.js>
"use strict";
const fs = require("fs");

const file = process.argv[2];
if (!file) {
    console.error("usage: node tools/add_test_plugin.js <path to plugins.js>");
    process.exit(2);
}
const text = fs.readFileSync(file, "utf8");
const plugins = JSON.parse(text.slice(text.indexOf("["), text.lastIndexOf("]") + 1));
if (!plugins.some(p => p.name === "UF_Test")) {
    plugins.push({ name: "UF_Test", status: true, description: "[UF Test] PASS/FAIL test harness. Does nothing unless the game is launched with --uf-test.", parameters: {} });
}
const body = plugins.map(p => JSON.stringify(p)).join(",\n");
fs.writeFileSync(file, `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${body}\n];\n`);
console.log(`${file}: ${plugins.length} plugins, UF_Test registered`);
