// Registers plugins (default: UF_Test) at the end of a plugins.js file, in the order given.
// For disposable test copies of the game; the real plugins.js is managed by the RMMZ editor.
// Usage: node tools/add_test_plugin.js <path to plugins.js> [PluginName ...]
"use strict";
const fs = require("fs");

const [file, ...names] = process.argv.slice(2);
if (!file) {
    console.error("usage: node tools/add_test_plugin.js <path to plugins.js> [PluginName ...]");
    process.exit(2);
}
const wanted = names.length ? names : ["UF_Test"];
const text = fs.readFileSync(file, "utf8").replace(/^﻿/, "");
const plugins = JSON.parse(text.slice(text.indexOf("["), text.lastIndexOf("]") + 1));
for (const name of wanted) {
    if (!plugins.some(p => p.name === name)) {
        plugins.push({ name, status: true, description: `[${name}]`, parameters: {} });
    }
}
const body = plugins.map(p => JSON.stringify(p)).join(",\n");
fs.writeFileSync(file, `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${body}\n];\n`);
console.log(`${file}: ${plugins.length} plugins; registered ${wanted.join(", ")}`);
