// bench_combat_srd.js - SIM.60.06. Re-run the WG.00.09b combat stress with SRD 5.1
// stat-block units. UF.Rules attack/damage time is recorded apart from render time.
// The driver visits only fighters whose action is due (resolution fullScans stays 0).
//
// Usage:
//   node tools/bench_combat_srd.js --self-test
//   node tools/bench_combat_srd.js [--runs n] [--seconds 30] [--mode both|base|srd] [--keep]
//
// The heavy path copies game/ under %TEMP%, raises that copy's harness watchdog
// (the stock watchdog is 180 s; a 30 s day/night pair plus the base pair does not fit),
// and deletes the copy afterwards. It does not write under game/.
// machineLoad is recorded for the run. --mode both is the same-session base rerun:
// render stress with resolution off, then the same window with UF.Rules on.
// Exit: 0 measured (or self-test passed); 1 a run finished without its checks; 2 harness.
"use strict";
const fs = require("fs");
const path = require("path");
const os = require("os");
const { spawn, spawnSync, execFileSync } = require("child_process");
const load = require("./bench/combat_srd/load");

const args = process.argv.slice(2);
const opt = (name, fallback) => {
    const i = args.indexOf(name);
    return i >= 0 && args[i + 1] !== undefined ? args[i + 1] : fallback;
};

if (args.includes("--self-test")) {
    require("./bench/combat_srd/self_test").run();
}

const root = path.resolve(__dirname, "..");
const lib = path.join(__dirname, "bench", "combat_srd");
const runs = Math.max(1, parseInt(opt("--runs", "1"), 10) || 1);
const seconds = Math.max(1, parseInt(opt("--seconds", "30"), 10) || 30);
const mode = opt("--mode", "both");
if (["both", "base", "srd"].indexOf(mode) < 0) {
    console.error("HARNESS: --mode is both, base or srd");
    process.exit(2);
}
const keepSnapshot = args.includes("--keep");
const NW = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\RPG Maker MZ\\nwjs-win\\nw.exe";
const RUN_TIMEOUT_MS = 720000;
const git = (...a) => execFileSync("git", a, { cwd: root, encoding: "utf8" }).trim();
const headSha = git("rev-parse", "HEAD");
const sha8 = headSha.slice(0, 8);
const outDir = path.join(root, "tasks", "SIM.60.06", "lane-ah", "perf");
fs.mkdirSync(outDir, { recursive: true });
const outBase = path.join(outDir, "combat_srd_" + sha8);
let outFile = outBase + ".json";
for (let n = 2; fs.existsSync(outFile) && !args.includes("--force"); n++) outFile = outBase + "_" + n + ".json";

function removeSnapshot(dir) {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name);
        if (entry.isSymbolicLink() || fs.lstatSync(p).isSymbolicLink()) fs.unlinkSync(p);
        else fs.rmSync(p, { recursive: true, force: true });
    }
    fs.rmdirSync(dir);
}

function makeSnapshot(name) {
    const dir = path.join(os.tmpdir(), "uf_snapshots", name);
    const r = spawnSync(process.execPath, [path.join(__dirname, "test_snapshot.js"), "--name", name, "--plugins", "DEUS_Depth", "--dir", dir, "--no-run"], { encoding: "utf8" });
    if (r.status !== 0) {
        console.error(r.stdout || "", r.stderr || "");
        throw new Error("snapshot failed");
    }
    const testJs = path.join(dir, "js", "plugins", "DEUS_Test.js");
    const needle = 'setTimeout(() => finish(2, "watchdog: whole run took longer than 180 s"), 180000);';
    const text = fs.readFileSync(testJs, "utf8");
    if (text.indexOf(needle) < 0) throw new Error("snapshot watchdog string missing");
    fs.writeFileSync(testJs, text.replace(needle, 'setTimeout(() => finish(2, "watchdog: whole run took longer than 600 s"), 600000);'));
    fs.copyFileSync(path.join(lib, "DEUS_BenchCombatSrd.js"), path.join(dir, "js", "plugins", "DEUS_BenchCombatSrd.js"));
    const pluginsFile = path.join(dir, "js", "plugins.js");
    const pluginsText = fs.readFileSync(pluginsFile, "utf8").replace(/^\uFEFF/, "");
    const list = JSON.parse(pluginsText.slice(pluginsText.indexOf("["), pluginsText.lastIndexOf("]") + 1)).filter(p => p.name !== "DEUS_BenchCombatSrd");
    const tests = list.filter(p => p.name === "UF_Test" || p.name === "DEUS_Test");
    const rest = list.filter(p => tests.indexOf(p) < 0);
    if (!tests.some(p => p.name === "UF_Test")) tests.push({ name: "UF_Test", status: true, description: "[UF_Test]", parameters: {} });
    for (const p of tests) p.status = true;
    const out = rest.concat([{ name: "DEUS_BenchCombatSrd", status: true, description: "[bench] SIM.60.06", parameters: {} }], tests);
    fs.writeFileSync(pluginsFile, "// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n" + out.map(p => JSON.stringify(p)).join(",\n") + "\n];\n");
    return dir;
}

function runGame(dir) {
    const resultsFile = path.join(dir, "test_output", "results.txt");
    fs.rmSync(resultsFile, { force: true });
    const profileName = "uf_test_profile_" + process.pid + "_" + Date.now();
    const profileDir = path.join(os.tmpdir(), profileName);
    const noThrottle = ["--disable-background-timer-throttling", "--disable-renderer-backgrounding", "--disable-backgrounding-occluded-windows", "--disable-features=CalculateNativeWinOcclusion"];
    const own = { profile: profileName, rootPid: null };
    const loadStart = load.procs(own);
    const cpu = load.cpuSampler();
    const during = [];
    const procTimer = setInterval(() => { load.procsAsync(own).then(p => during.push(p)); }, 15000);
    const child = spawn(NW, [dir, "--user-data-dir=" + profileDir].concat(noThrottle, ["--deus-test=bench_combat_srd"]), {
        env: Object.assign({}, process.env, {
            BENCH_OUT: path.join(dir, "test_output", "bench.json"),
            BENCH_LIB: lib,
            BENCH_SECONDS: String(seconds),
            BENCH_MODE: mode
        }),
        stdio: ["ignore", "ignore", "ignore"]
    });
    own.rootPid = child.pid;
    let exitCode = null;
    const exitP = new Promise(res => child.on("exit", code => { exitCode = code; res(); }));
    const killer = setTimeout(() => {
        try { execFileSync("taskkill", ["/PID", String(child.pid), "/T", "/F"], { stdio: "ignore" }); } catch (e) { /* gone */ }
    }, RUN_TIMEOUT_MS);
    const t0 = Date.now();
    return exitP.then(() => {
        clearTimeout(killer);
        cpu.stop();
        clearInterval(procTimer);
        const loadEnd = load.procs(own);
        try { fs.rmSync(profileDir, { recursive: true, force: true }); } catch (e) { /* locked */ }
        const text = fs.existsSync(resultsFile) ? fs.readFileSync(resultsFile, "utf8") : "";
        const m = text.match(/^RESULT: (\d+) passed, (\d+) failed \(exit (\d)\)$/m);
        return {
            status: m ? Number(m[3]) : 2,
            text: text,
            seconds: +((Date.now() - t0) / 1000).toFixed(1),
            nwExit: exitCode,
            load: { start: loadStart, end: loadEnd, during: during, cpuSamples: cpu.samples }
        };
    });
}

(async () => {
    if (!fs.existsSync(NW)) {
        console.error("HARNESS: nw.exe not found at " + NW);
        process.exit(2);
    }
    console.log("=== bench_combat_srd: mode " + mode + ", " + seconds + "s phases, " + runs + " run(s), " + sha8 + " ===");
    const report = {
        task: "SIM.60.06",
        lane: "lane-ah",
        mode: mode,
        seconds: seconds,
        measuredSha: headSha,
        machine: { host: os.hostname(), cpus: os.cpus().length, cpu: os.cpus()[0] && os.cpus()[0].model, totalMemGb: +(os.totalmem() / 2 ** 30).toFixed(1) },
        method: "nw.exe harness (--deus-test=bench_combat_srd) on a snapshot copy of game/ under %TEMP%. The copy's DEUS_Test watchdog is raised from 180 s to 600 s so a day/night base pass and a day/night SRD pass fit in one process. Fighters carry SRD stat-block ids from tools/bench/combat_srd/roster.js. Resolution is UF.Rules.attack and UF.Rules.damage (host resolveAttack when the catalog weapon key is that action). sim.rules and render are separate timers. The driver is a due bucket; resolution.fullScans counts roster walks. Machine load: runs[].machineLoad.",
        runs: []
    };
    let failures = 0;
    let harness = 0;
    for (let i = 0; i < runs; i++) {
        const runNo = i + 1;
        const name = "laneah_combat_srd_" + sha8 + "_" + process.pid + "_" + Date.now();
        const dir = makeSnapshot(name);
        const json = path.join(dir, "test_output", "bench.json");
        fs.rmSync(json, { force: true });
        console.log("  run " + runNo + ": snapshot " + dir);
        const r = await runGame(dir);
        for (const line of r.text.split(/\r?\n/)) {
            if (/^(BENCH|PASS|FAIL|ERROR|HARNESS|RESULT)/.test(line)) console.log("  run " + runNo + ": " + line);
        }
        const data = fs.existsSync(json) ? JSON.parse(fs.readFileSync(json, "utf8")) : null;
        if (!keepSnapshot) {
            try { removeSnapshot(dir); } catch (e) { console.log("  run " + runNo + ": could not remove " + dir + ": " + e.message); }
        }
        if (!data) {
            console.error("  run " + runNo + ": no numbers written (exit " + r.status + ", " + r.seconds + " s)");
            if (r.status === 2) harness++;
            else failures++;
            continue;
        }
        data.run = runNo;
        data.wallSeconds = r.seconds;
        data.exit = r.status;
        data.machineLoad = load.machineLoad(r.load, data.phases || []);
        report.runs.push(data);
        const ml = data.machineLoad;
        console.log("  run " + runNo + ": machine load " + ml.label + ": CPU median " + ml.cpu.overall.median + " % (min " + ml.cpu.overall.min + ", max " + ml.cpu.overall.max + "); AI workers " + ml.start.aiWorkers + " -> " + ml.end.aiWorkers + "; other nw.exe " + ml.start.otherNwExe + " / max " + ml.otherNwExeMax);
        if (r.status !== 0) failures++;
    }
    report.writtenAt = new Date().toISOString();
    if (report.runs.length) {
        fs.writeFileSync(outFile, JSON.stringify(report, null, 1));
        console.log("wrote " + path.relative(root, outFile));
    } else {
        console.log("no run produced numbers: nothing written");
    }
    for (let i = 0; i < report.runs.length; i++) {
        const run = report.runs[i];
        const phases = run.phases || [];
        for (let p = 0; p < phases.length; p++) {
            const row = phases[p];
            console.log("  run " + run.run + " " + row.phase + " frame median " + row.frameMs.median + " ms (" + row.fps.atMedian + " fps, target " + (row.target && row.target.met ? "met" : "missed") + ") sim " + row.simMs.median + " ms render " + row.renderMs.median + " ms fullScans " + (row.resolution && row.resolution.fullScans));
        }
        if (run.resolution) console.log("  run " + run.run + " resolution fullScans " + run.resolution.fullScans + " maxDue " + run.resolution.maxDue + " / " + run.resolution.population + " fromStatBlock " + run.resolution.fromStatBlock + "/" + run.resolution.rulesCalls);
    }
    const code = report.runs.length === runs && failures === 0 ? 0 : (harness ? 2 : 1);
    console.log("exit " + code);
    process.exit(code);
})();
