// Registers the world-build plugins in game/js/plugins.js in the order docs/design/WORLD_ARCHITECTURE.md §5 gives,
// keeping every existing entry and its parameters. Run only with the RMMZ editor closed (ENGINE_RULES §3).
// Usage: node tools/register_world_plugins.js [--dry]
"use strict";
const fs = require("fs");
const path = require("path");

const file = path.join(__dirname, "..", "game", "js", "plugins.js");
const dry = process.argv.includes("--dry");
// The order after UF_ProcGen. Entries not yet on disk are skipped with a warning.
const ORDER = ["UF_World", "UF_WorldGen", "UF_Tiles", "UF_Factions", "UF_History", "UF_Objects", "UF_Items", "UF_Jobs",
    "UF_Colonists", "UF_Wildlife", "UF_Stance", "UF_Fog", "UF_DayNight", "UF_TimeSpeed", "UF_Camera", "UF_Look", "UF_Interact", "UF_Test"];
const DESCRIPTIONS = {
    UF_Tiles: "[UF Tiles] Ground kinds drawn in code and the runtime world tileset (91).",
    UF_Objects: "[UF Objects] Per-cell world objects (plants, stones, buildings): drawing, passability, actions, regrowth.",
    UF_Items: "[UF Items] Items on the ground, in stacks and in inventories.",
    UF_Jobs: "[UF Jobs] DF-style jobs: walk to a target, work, change the world (gather, chop, haul, build, craft, hunt...).",
    UF_Colonists: "[UF Colonists] The pair as world units: needs, personality, daily pattern, the society plan.",
    UF_Wildlife: "[UF Wildlife] Creatures spawned with the map by biome; wander and flee.",
    UF_Stance: "[UF Stance] Green / yellow / red squares under units by stance toward the colony.",
    UF_Look: "[UF Look] Look label under the mouse: what's there, biome, art file and its status.",
    UF_Interact: "[UF Interact] Right-click anything for its interaction options; choices become jobs."
};

const text = fs.readFileSync(file, "utf8").replace(/^﻿/, "");
const list = JSON.parse(text.slice(text.indexOf("["), text.lastIndexOf("]") + 1));
const byName = new Map(list.map(p => [p.name, p]));
const pluginsDir = path.join(__dirname, "..", "game", "js", "plugins");

const before = list.filter(p => !ORDER.includes(p.name));
const ordered = [];
for (const name of ORDER) {
    if (!fs.existsSync(path.join(pluginsDir, `${name}.js`))) {
        console.warn(`skip ${name}: no game/js/plugins/${name}.js`);
        continue;
    }
    const existing = byName.get(name);
    ordered.push(existing || { name, status: true, description: DESCRIPTIONS[name] || `[${name}]`, parameters: {} });
}
const result = [...before, ...ordered];
const out = `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${result.map(p => JSON.stringify(p)).join(",\n")}\n];\n`;
console.log(result.map(p => p.name).join(" > "));
if (dry) {
    console.log("(dry run: nothing written)");
} else {
    fs.writeFileSync(file, out);
    console.log(`wrote ${file} (${result.length} plugins)`);
}
