#!/usr/bin/env node
"use strict";
/**
 * tools/test_zrange.js - WG.00.17 lane AA: the Z range as one setting, 32 layers (-16..+15), sparse storage in memory
 * and saves, 2 ft strata / 10 ft layers / 5 ft squares, the 9-layer test mode and old 5-level saves.
 *
 * Runs the real game in NW.js on per-run snapshot copies of game/ under %TEMP% (printed, deleted after), with a
 * test-only plugin (DEUS_TestZRange.js, the suite "zrange", tools/zrange/zrange_suite.js) and a pinned world seed.
 * Each configuration (a Z range, passed to the game as DEUS_Z_RANGE) runs the phases core and play in their own NW.js
 * runs (DEUS_Test stops a run after 180 s); the legacy phase loads a save written by the base commit.
 *
 * Checks (PASS/FAIL lines, then RESULT). Each has a provocation (--provoke) that must make it FAIL:
 *   single_authority      the static scan finds no Z literal outside the allow-list (tools/zrange/scan_z_literals.js) and,
 *                         at each range, the in-game probe accepts exactly zMin..zMax (isLevel, inWorld, map ids, labels,
 *                         addUnit, Items.drop, Objects.setIn, strataAt, shapeAt, the level list)
 *   elevation_math        e = (z - zMin) * 5 + s both ways on the lowest, highest and core levels, no cap at 24
 *   feet_2ft_10ft         UF.Space is 5 ft / 2 ft / 5 strata / 10 ft, and the blast fixture's destroyed strata equal the
 *                         2 ft table at the tip (tools/zrange/blast_tables.js) and the 1 ft table at the base commit
 *   sparse_memory         outside -2..+2 every chunk is UNIFORM except the mountain rock above +2 (counted), a first
 *                         write to a sky cell splits one chunk, and the baseline storage at -16..+15 minus -2..+2 stays
 *                         within the bound derived from the directory size (tools/zrange/bounds.js)
 *   sparse_save           a fresh world's save at -16..+15 is at most 256 B larger in its terrain and fluid parts than
 *                         at -4..+4; a change on +12 and on -14 adds only its record; save and load round-trip the cells
 *   legacy_save_loads     a save written by the base commit loads at -2..+2 with every cell, unit and item identical, and
 *                         stays at -2..+2 after another save and load
 *   old_layers_identical  the core levels -2..+2 of the pinned seed: checksums, generated bytes and every cell's strata
 *                         and shape identical to the base commit's, at every range
 *   matter_unchanged      the census (strata by material on -2..+2, the rock above +2 against the base's caps, objects,
 *                         items, units) and the ledger's totals per class (game/js/sim/ledger.js, read only) identical to
 *                         the base commit's after New Game and after ZR_UPDATES map updates
 *   extreme_layers_work   on the top and bottom levels a unit stands, walks and paths, the view switches there in place
 *                         and view stepping stops at the ends, no errors
 *   path_scratch_bounded  a 3D search on one level allocates scratch for the levels it reached only (counted)
 *
 * Usage: node tools/test_zrange.js [--z-range=<zMin>..<zMax>] [--seed=18] [--base=<sha>] [--updates=3000]
 *                                  [--refresh-base] [--make-legacy-fixture] [--provoke=<check> | --provoke-all]
 *                                  [--evidence=<dir>] [--keep] [--jobs=n]
 *   (no --z-range: the three configurations -4..4, -16..15 and the legacy -2..2)
 *   --refresh-base          run the base commit (a temp clone) and rewrite tools/zrange/fixtures/base_<sha8>_seed<n>.json
 *   --make-legacy-fixture   run make_legacy on the base commit and write tools/zrange/fixtures/legacy_save_<sha8>_seed<n>.json.gz
 *   --phase=<p> [--commit=<sha>]  run one phase (core, play, sim, legacy) on the configurations (default: this tree; with
 *                           --commit, a temp clone of that commit) and print the suite's lines and report (diagnostics)
 * Exit: 0 all checks passed (with --provoke: every provocation caught); 1 a check failed / a provocation not caught;
 *       2 harness problem.
 */
const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync, spawn, execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..");
const ZR = path.join(__dirname, "zrange");
const FIX = path.join(ZR, "fixtures");
const args = process.argv.slice(2);
const arg = (name, fallback) => { const a = args.find(x => x.startsWith(`--${name}=`)); return a ? a.slice(name.length + 3) : fallback; };
const flag = name => args.includes(`--${name}`);
const SEED = Number(arg("seed", "18"));
const BASE = arg("base", "5255f1a58a9d95bb7bc08377ef055c366610e486");
const UPDATES = Number(arg("updates", "2400"));
const KEEP = flag("keep");
const RUN_TIMEOUT = 420000;
const CONFIGS = arg("z-range", "") ? [arg("z-range", "")] : ["-4..4", "-16..15", "-2..2"];
const CHECKS = ["single_authority", "elevation_math", "feet_2ft_10ft", "sparse_memory", "sparse_save", "legacy_save_loads", "old_layers_identical",
    "matter_unchanged", "extreme_layers_work", "path_scratch_bounded"];
const { scan, loadAllow, judge } = require("./zrange/scan_z_literals.js");
const { blastTable } = require("./zrange/blast_tables.js");
const { memoryBound, SAVE_BOUND } = require("./zrange/bounds.js");
const { zrangeSuitePlugin } = require("./zrange/zrange_suite.js");
const { PROVOCATIONS } = require("./zrange/provocations.js");

const log = (...a) => console.log(...a);
const sha8 = s => String(s).slice(0, 8);
const baseFixtureFile = () => path.join(FIX, `base_${sha8(BASE)}_seed${SEED}.json`);
const legacyFiles = () => ({ save: path.join(FIX, `legacy_save_${sha8(BASE)}_seed${SEED}.json.gz`), fingerprint: path.join(FIX, `legacy_fingerprint_${sha8(BASE)}_seed${SEED}.json`) });
/** The legacy save fixture, gunzipped to a temp file for the game to read (ZR_SAVE). */
function legacySaveFile() {
    const lf = legacyFiles();
    if (!fs.existsSync(lf.save)) return null;
    const out = path.join(os.tmpdir(), `laneaa_zr_legacy_save_${process.pid}.json`);
    fs.writeFileSync(out, require("zlib").gunzipSync(fs.readFileSync(lf.save)));
    return out;
}

//-----------------------------------------------------------------------------
// Snapshots and runs

/** Delete a folder without following junctions (snapshot asset folders are junctions to the real ones). */
function removeTree(dir) {
    if (!fs.existsSync(dir)) return;
    if (fs.lstatSync(dir).isSymbolicLink()) { fs.unlinkSync(dir); return; }
    for (const e of fs.readdirSync(dir)) {
        const p = path.join(dir, e), l = fs.lstatSync(p);
        if (l.isSymbolicLink()) fs.unlinkSync(p);
        else if (l.isDirectory()) removeTree(p);
        else fs.rmSync(p, { force: true });
    }
    fs.rmdirSync(dir);
}
/** A snapshot of <gameDir> under %TEMP%: js/, data/, index.html, package.json copied, the rest junctions (tools/test_snapshot.js's pattern). */
function makeSnapshot(gameDir, tag, edits) {
    const dir = path.join(os.tmpdir(), "laneaa_zr_snap", `${tag}_${process.pid}_${Date.now()}`);
    removeTree(dir);
    fs.mkdirSync(dir, { recursive: true });
    const COPY = ["js", "data", "index.html", "package.json"];
    for (const e of fs.readdirSync(gameDir, { withFileTypes: true })) {
        const src = path.join(gameDir, e.name), dst = path.join(dir, e.name);
        if (["test_output", "save", "game_runtime.log", "test_screenshot.png"].includes(e.name)) continue;
        if (COPY.includes(e.name)) fs.cpSync(src, dst, { recursive: true });
        else if (e.isDirectory()) fs.symlinkSync(src, dst, "junction");
        else fs.copyFileSync(src, dst);
    }
    fs.mkdirSync(path.join(dir, "test_output"), { recursive: true });
    // Provocation edits: exact source edits, each target exactly once.
    for (const [file, from, to] of edits || []) {
        const p = path.join(dir, "js", "plugins", file);
        const src = fs.readFileSync(p, "utf8").replace(/\r\n/g, "\n");
        const n = src.split(from).length - 1;
        if (n !== 1) throw new Error(`provocation edit: target occurs ${n} times in ${file}: ${from.slice(0, 80)}`);
        fs.writeFileSync(p, src.replace(from, () => to));
    }
    fs.writeFileSync(path.join(dir, "js", "plugins", "DEUS_TestZRange.js"),
        `// Test-only plugin written by tools/test_zrange.js into a snapshot copy. Never part of the game.\n(${zrangeSuitePlugin.toString()})();\n`);
    const pj = path.join(dir, "js", "plugins.js");
    const text = fs.readFileSync(pj, "utf8").replace(/^﻿/, "");
    const plugins = JSON.parse(text.slice(text.indexOf("["), text.lastIndexOf("]") + 1));
    const world = plugins.find(p => p.name === "DEUS_World");
    if (!world) throw new Error("DEUS_World is not in plugins.js");
    world.parameters = Object.assign({}, world.parameters, { Seed: String(SEED) });
    if (!plugins.some(p => p.name === "DEUS_Test" && p.status)) throw new Error("DEUS_Test is not registered");
    plugins.push({ name: "DEUS_TestZRange", status: true, description: "[test only] WG.00.17 zrange suite", parameters: {} });
    fs.writeFileSync(pj, `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${plugins.map(p => JSON.stringify(p)).join(",\n")}\n];\n`);
    // A forced garbage collection for the heap numbers: --expose-gc in the snapshot's chromium args (the snapshot only).
    const pk = path.join(dir, "package.json");
    const pkg = JSON.parse(fs.readFileSync(pk, "utf8"));
    pkg["chromium-args"] = `${pkg["chromium-args"] || ""} --js-flags=--expose-gc`.trim();
    fs.writeFileSync(pk, JSON.stringify(pkg, null, 2));
    return dir;
}
/** One NW.js run of the suite on a snapshot: resolves { status, checks: { name: { pass, detail } }, result, report, text, secs }. */
async function runPhase(clone, label, env, edits) {
    const gameDir = path.join(clone, "game");
    const snap = makeSnapshot(gameDir, label.replace(/[^\w.-]/g, "_"), edits);
    const t0 = Date.now();
    const e = Object.assign({}, process.env, env, { ZR_UPDATES: String(UPDATES) });
    if (env.DEUS_Z_RANGE === null) delete e.DEUS_Z_RANGE;
    const r = await new Promise(resolve => {
        const child = spawn(process.execPath, [path.join(clone, "tools", "run_tests.js"), "zrange", "--game", snap], { env: e, stdio: ["ignore", "pipe", "pipe"] });
        child.stdout.on("data", () => {});
        child.stderr.on("data", () => {});
        const timer = setTimeout(() => { try { child.kill(); } catch (_) { /* gone */ } }, RUN_TIMEOUT);
        child.on("exit", status => { clearTimeout(timer); resolve({ status }); });
    });
    const out = path.join(snap, "test_output");
    const text = fs.existsSync(path.join(out, "results.txt")) ? fs.readFileSync(path.join(out, "results.txt"), "utf8") : "";
    let report = null;
    try { report = JSON.parse(fs.readFileSync(path.join(out, "zrange_report.json"), "utf8")); } catch (_) { report = null; }
    const checks = {};
    for (const m of text.matchAll(/^(PASS|FAIL) zrange\.(\w+)(?: - (.*))?$/gm)) checks[m[2]] = { pass: m[1] === "PASS", detail: m[3] || "" };
    const result = (text.match(/^RESULT: .*$/m) || [null])[0];
    const secs = ((Date.now() - t0) / 1000).toFixed(0);
    const ev = arg("evidence", "");
    if (ev) {
        const dst = path.join(path.resolve(ev), label.replace(/[^\w.-]/g, "_"));
        fs.mkdirSync(dst, { recursive: true });
        for (const f of fs.existsSync(out) ? fs.readdirSync(out) : []) if (f === "results.txt" || f === "zrange_report.json" || (f.startsWith("zrange.") && f.endsWith(".png"))) fs.copyFileSync(path.join(out, f), path.join(dst, f));
    }
    if (!KEEP) { try { removeTree(snap); } catch (err) { log(`  (could not delete ${snap}: ${err.message})`); } }
    log(`  run ${label}: ${result || "NO RESULT LINE"} in ${secs} s (run_tests exit ${r.status}); snapshot ${snap}${KEEP ? "" : " (deleted)"}`);
    for (const line of text.split(/\r?\n/)) if (/^(FAIL|ERROR|HARNESS)/.test(line)) log(`    ${line.slice(0, 400)}`);
    return { status: r.status, checks, result, report, text, secs, snap };
}

//-----------------------------------------------------------------------------
// Base data (the base commit, a temp clone): the core hashes, the census before and after play, the blast table.

function baseClone(tag) {
    const { makeClone } = require("./zrange/clone.js");
    return makeClone(BASE, `base_${sha8(BASE)}_${tag}`).dir;
}
async function refreshBase() {
    const clone = baseClone("fixture");
    log(`base ${BASE} cloned at ${clone}`);
    const [core, core2, play, sim, sim2] = await pool([
        () => runPhase(clone, `base_core`, { ZR_PHASE: "core", DEUS_Z_RANGE: null }),
        () => runPhase(clone, `base_core_again`, { ZR_PHASE: "core", DEUS_Z_RANGE: null }),
        () => runPhase(clone, `base_play`, { ZR_PHASE: "play", DEUS_Z_RANGE: null }),
        () => runPhase(clone, `base_sim`, { ZR_PHASE: "sim", DEUS_Z_RANGE: null }),
        () => runPhase(clone, `base_sim_again`, { ZR_PHASE: "sim", DEUS_Z_RANGE: null })]);
    if (!core.report || !play.report || !sim.report) throw new Error("the base runs wrote no report");
    const d = { base: BASE, seed: SEED, updates: UPDATES, made: new Date().toISOString(), by: "node tools/test_zrange.js --refresh-base",
        core: core.report.data.core, census: core.report.data.census, blast: core.report.data.blast, saveFresh: play.report.data.saveFresh,
        censusAfter: sim.report.data.censusAfter, simulation: sim.report.data.simulation, timing: core.report.timing, heapAfterNewGame: core.report.data.heapAfterNewGame,
        memoryBase: core.report.data.memoryBase,
        repeat: { coreSame: JSON.stringify(core2.report && core2.report.data.core) === JSON.stringify(core.report.data.core),
            censusSame: JSON.stringify(core2.report && core2.report.data.census && strip(core2.report.data.census)) === JSON.stringify(strip(core.report.data.census)),
            censusAfterSame: JSON.stringify(sim2.report && sim2.report.data.censusAfter && strip(sim2.report.data.censusAfter)) === JSON.stringify(strip(sim.report.data.censusAfter)),
            censusAfterAgain: sim2.report ? strip(sim2.report.data.censusAfter) : null, simulationAgain: sim2.report ? sim2.report.data.simulation : null } };
    fs.mkdirSync(FIX, { recursive: true });
    fs.writeFileSync(baseFixtureFile(), JSON.stringify(d, null, 1) + "\n");
    log(`wrote ${baseFixtureFile()} (repeat: ${JSON.stringify({ coreSame: d.repeat.coreSame, censusSame: d.repeat.censusSame, censusAfterSame: d.repeat.censusAfterSame })})`);
    if (!KEEP) require("./zrange/clone.js").removeTree(clone);
}
async function makeLegacyFixture() {
    const clone = baseClone("legacy");
    const tmp = path.join(os.tmpdir(), "laneaa_zr_legacy");
    removeTree(tmp);
    const r = await runPhase(clone, "base_make_legacy", { ZR_PHASE: "make_legacy", DEUS_Z_RANGE: null, ZR_OUT_DIR: tmp });
    if (!r.checks.legacy_fixture_written || !r.checks.legacy_fixture_written.pass) throw new Error("make_legacy failed");
    const lf = legacyFiles();
    fs.mkdirSync(FIX, { recursive: true });
    fs.writeFileSync(lf.save, require("zlib").gzipSync(fs.readFileSync(path.join(tmp, "legacy_save.json")), { level: 9 }));
    const fp = JSON.parse(fs.readFileSync(path.join(tmp, "legacy_fingerprint.json"), "utf8"));
    fp.base = BASE;
    fs.writeFileSync(lf.fingerprint, JSON.stringify(fp, null, 1) + "\n");
    log(`wrote ${lf.save} (${fs.statSync(lf.save).size} B) and ${lf.fingerprint}`);
    removeTree(tmp);
    if (!KEEP) require("./zrange/clone.js").removeTree(clone);
}
const strip = c => { if (!c) return c; const o = Object.assign({}, c); delete o.ms; return o; };

//-----------------------------------------------------------------------------
// The checks

// Matter doesn't depend on where it is: items and units are compared by type and kind summed over the levels (a unit
// that walks up a ramp takes its pack with it; the base commit's own two runs differ only there). Strata and objects are
// per material and type on the core levels.
const byType = o => { const out = {}; for (const k in o || {}) { const t = k.replace(/:-?\d+$/, ""); out[t] = (out[t] || 0) + o[k]; } return out; };
function censusDiff(a, b) {
    const out = [];
    for (const key of ["strata", "objects", "items", "units"]) {
        const ka = key === "items" || key === "units" ? byType(a[key]) : a[key] || {}, kb = key === "items" || key === "units" ? byType(b[key]) : b[key] || {};
        for (const k of new Set([...Object.keys(ka), ...Object.keys(kb)])) if ((ka[k] || 0) !== (kb[k] || 0)) out.push(`${key}.${k}: ${ka[k] || 0} vs ${kb[k] || 0}`);
    }
    return out;
}
/** The census as ledger registrations: strata by material, objects and items by their catalog class where one maps. */
function ledgerTotals(census, ledgerPath) {
    const { createLedger } = require(ledgerPath);
    const led = createLedger();
    const unmapped = {};
    const put = (cls, form, n, what) => { if (!n) return; try { led.register(cls, form, n, what); } catch (e) { unmapped[what] = (unmapped[what] || 0) + n; } };
    const MAT = { 1: "stone", 2: "soil", 3: "wood", 4: "water", 5: "lava" };
    for (const k in census.strata) {
        const b = Number(k), id = b & 63, built = (b & 0x80) !== 0, cls = MAT[id];
        if (!cls) { unmapped[`strata:${k}`] = census.strata[k]; continue; }
        const form = cls === "water" || cls === "lava" ? "fluid" : built ? "object" : "strata";
        put(cls, form, census.strata[k], `strata:${k}`);
    }
    if (census.capStrata) put("stone", "strata", census.capStrata, "caps above +2");
    for (const k in census.objects) unmapped[`object:${k}`] = census.objects[k];   // objects and items keep their own counts (compared raw)
    for (const k in census.items) unmapped[`item:${k}`] = census.items[k];
    led.seal();
    return { totals: led.totals().classes, families: led.totals().families, checksum: led.checksum(), unmappedKeys: Object.keys(unmapped).length };
}

function evaluate(results, base, provoked) {
    const out = {};
    const cfgs = Object.keys(results).filter(k => k !== "__legacy");
    const inGame = (cfg, phase, name) => { const r = results[cfg][phase]; return r && r.checks[name] ? r.checks[name] : { pass: false, detail: `the check ${name} did not run (${r ? r.result : "no run"})` }; };
    const reportOf = (cfg, phase) => (results[cfg][phase] && results[cfg][phase].report ? results[cfg][phase].report.data : null);

    // single_authority: the static scan (on this tree or the provocation's edited copy) and every range's probe.
    {
        const root = provoked && provoked.scanRoot ? provoked.scanRoot : ROOT;
        const s = judge(scan(root), loadAllow(path.join(ZR, "z_literal_allowlist.json")));
        const probes = cfgs.map(c => ({ c, r: inGame(c, "core", "single_authority_ingame") }));
        out.single_authority = { pass: s.bad.length === 0 && s.stale.length === 0 && probes.every(p => p.r.pass),
            detail: `static scan: ${s.hits} lines with a Z pattern, ${s.allowed} allowed (${s.entries} entries), ${s.bad.length} not allowed${s.bad.length ? ` (${s.bad.slice(0, 3).map(h => `${h.file}:${h.line} ${h.text.slice(0, 60)}`).join(" | ")})` : ""}, ${s.stale.length} stale; in-game: ${probes.map(p => `${p.c} ${p.r.pass ? "PASS" : "FAIL"}`).join(", ")}` };
    }
    out.elevation_math = { pass: cfgs.every(c => inGame(c, "core", "elevation_math").pass), detail: cfgs.map(c => `${c}: ${inGame(c, "core", "elevation_math").detail.slice(0, 220)}`).join(" || ") };
    {
        const want2 = blastTable(2), want1 = blastTable(1), rows = [];
        let ok = true;
        for (const c of cfgs) {
            const d = reportOf(c, "core"), k = inGame(c, "core", "feet_constants");
            const got = d && d.blast && d.blast.radii;
            const same = !!got && [3, 5, 7].every(R => JSON.stringify(got[R].hits) === JSON.stringify(want2[R]));
            if (!(k.pass && same)) ok = false;
            rows.push(`${c}: constants ${k.pass ? "ok" : "WRONG"}, blast ${same ? "= 2 ft table" : "DIFFERS from the 2 ft table"} (${got ? [3, 5, 7].map(R => `r${R} ${got[R].hits.length}`).join(", ") : "none"})`);
        }
        const bb = base && base.blast && base.blast.radii;
        const baseSame = !!bb && [3, 5, 7].every(R => JSON.stringify(bb[R].hits) === JSON.stringify(want1[R]));
        out.feet_2ft_10ft = { pass: ok && baseSame, detail: `${rows.join("; ")}; base ${sha8(BASE)}: ${baseSame ? "= 1 ft table" : "DIFFERS from the 1 ft table"} (${bb ? [3, 5, 7].map(R => `r${R} ${bb[R].hits.length}`).join(", ") : "no base data"}); tables: 2 ft ${[3, 5, 7].map(R => `r${R} ${want2[R].length}`).join(", ")}, 1 ft ${[3, 5, 7].map(R => `r${R} ${want1[R].length}`).join(", ")} strata` };
    }
    {
        const rows = [];
        let ok = cfgs.every(c => inGame(c, "core", "sparse_outer_uniform").pass && inGame(c, "core", "sparse_split_one_chunk").pass);
        const big = cfgs.find(c => c === "-16..15"), leg = cfgs.find(c => c === "-2..2");
        if (big && leg) {
            const a = reportOf(big, "core"), b = reportOf(leg, "core");
            if (a && b && a.sparse && b.sparse) {
                const bound = memoryBound(a, b);
                const diff = bound.tall - bound.legacy;
                const heapDiff = a.heapAfterNewGame && b.heapAfterNewGame ? a.heapAfterNewGame.usedJSHeapSize - b.heapAfterNewGame.usedJSHeapSize : null;
                if (!(diff <= bound.bytes)) ok = false;
                rows.push(`baseline store (directories, MIXED arrays, caps) -16..+15 ${bound.tall} B, -2..+2 ${bound.legacy} B: difference ${diff} B, bound ${bound.bytes} B (${bound.derivation}); shape grids cached ${a.memory.shapeGrids} / ${b.memory.shapeGrids} B; JS heap after New Game (forced GC ${a.heapAfterNewGame.gc}): ${a.heapAfterNewGame.usedJSHeapSize} vs ${b.heapAfterNewGame.usedJSHeapSize} B (difference ${heapDiff} B, reported, not judged)`);
            } else { ok = false; rows.push("no storage numbers from -16..15 and -2..2"); }
        } else rows.push("(the -16..15 minus -2..2 bound needs both configurations)");
        rows.unshift(cfgs.map(c => `${c}: outer ${inGame(c, "core", "sparse_outer_uniform").pass ? "UNIFORM" : "WRONG"}, split ${inGame(c, "core", "sparse_split_one_chunk").pass ? "one chunk" : "WRONG"}`).join(", "));
        out.sparse_memory = { pass: ok, detail: rows.join("; ") };
    }
    {
        let ok = cfgs.every(c => inGame(c, "play", "sparse_save_changes").pass);
        const rows = [cfgs.map(c => `${c}: changes ${inGame(c, "play", "sparse_save_changes").pass ? "one record each, round trip ok" : "WRONG"}`).join(", ")];
        const big = cfgs.find(c => c === "-16..15"), nine = cfgs.find(c => c === "-4..4");
        if (big && nine) {
            const a = reportOf(big, "play"), b = reportOf(nine, "play");
            if (a && b) {
                const part = s => s.levels + s.zRange + s.fluid + s.fluidAlias;
                const diff = part(a.saveFresh) - part(b.saveFresh);
                if (!(diff <= SAVE_BOUND)) ok = false;
                rows.push(`fresh world, terrain and fluid parts (levels + zRange + fluid): -16..+15 ${part(a.saveFresh)} B, -4..+4 ${part(b.saveFresh)} B: difference ${diff} B (bound ${SAVE_BOUND} B); whole saves ${a.saveFresh.total} / ${b.saveFresh.total} characters`);
            } else { ok = false; rows.push("no save numbers"); }
        } else rows.push("(the 256 B bound needs -16..15 and -4..4)");
        out.sparse_save = { pass: ok, detail: rows.join("; ") };
    }
    {
        const r = results.__legacy;
        const c = r && r.checks.legacy_save_loads;
        out.legacy_save_loads = { pass: !!c && c.pass, detail: c ? c.detail.slice(0, 900) : `did not run (${r ? r.result : "no legacy run"})` };
    }
    {
        const rows = [];
        let ok = !!(base && base.core);
        for (const c of cfgs) {
            const d = reportOf(c, "core");
            const bad = [];
            if (!d || !d.core) { ok = false; rows.push(`${c}: no data`); continue; }
            for (const part of ["checksums", "regenerated", "baseline", "cells", "shapes"]) if (JSON.stringify(d.core[part]) !== JSON.stringify(base && base.core[part])) bad.push(part);
            if (bad.length) ok = false;
            rows.push(`${c}: ${bad.length ? `DIFFERENT ${bad.join(", ")} (${JSON.stringify(d.core.baseline)} vs ${JSON.stringify(base && base.core.baseline)})` : `identical (checksums ${Object.values(d.core.checksums).join(" ")})`}`);
        }
        out.old_layers_identical = { pass: ok, detail: `base ${sha8(BASE)} seed ${SEED}: ${rows.join("; ")}` };
    }
    {
        const rows = [];
        let ok = !!(base && base.census);
        const ledgerPath = path.join(provoked && provoked.clone ? provoked.clone : ROOT, "game", "js", "sim", "ledger.js");
        const lb = base && base.census ? ledgerTotals(base.census, ledgerPath) : null, lba = base && base.censusAfter ? ledgerTotals(base.censusAfter, ledgerPath) : null;
        for (const c of cfgs) {
            const d0 = reportOf(c, "core"), d1 = reportOf(c, "sim");
            if (!lb || !lba) { ok = false; rows.push(`${c}: no base census to compare with`); continue; }
            if (!d0 || !d0.census || !d1 || !d1.censusAfter) { ok = false; rows.push(`${c}: no census`); continue; }
            const diff0 = censusDiff(d0.census, base.census), diff1 = censusDiff(d1.censusAfter, base.censusAfter);
            const caps0 = d0.census.capStrata === base.census.capStrata;
            const l0 = ledgerTotals(d0.census, ledgerPath), l1 = ledgerTotals(d1.censusAfter, ledgerPath);
            const led0 = l0.checksum === lb.checksum, led1 = l1.checksum === lba.checksum;
            if (diff0.length || diff1.length || !caps0 || !led0 || !led1) ok = false;
            rows.push(`${c}: New Game ${diff0.length ? `DIFFERS (${diff0.slice(0, 4).join(", ")})` : "identical"}, rock above +2 ${d0.census.capStrata} strata (base caps ${base.census.capStrata}), ledger ${l0.checksum} (base ${lb.checksum}); ` +
                `after ${d1.simulation ? d1.simulation.updates : "?"} updates ${diff1.length ? `DIFFERS (${diff1.slice(0, 4).join(", ")})` : "identical"}, ledger ${l1.checksum} (base ${lba.checksum}); layers outside -2..+2: ${Object.keys(d0.census.outer || {}).length} material keys`);
        }
        out.matter_unchanged = { pass: ok, detail: `base ${sha8(BASE)} seed ${SEED} (base repeat: census ${base && base.repeat ? base.repeat.censusSame : "?"}, after play ${base && base.repeat ? base.repeat.censusAfterSame : "?"}): ${rows.join("; ")}` };
    }
    out.extreme_layers_work = { pass: cfgs.every(c => inGame(c, "play", "extreme_layers_work").pass && inGame(c, "play", "no_errors").pass && inGame(c, "core", "no_errors").pass),
        detail: cfgs.map(c => `${c}: ${inGame(c, "play", "extreme_layers_work").pass ? "PASS" : "FAIL"} ${inGame(c, "play", "extreme_layers_work").detail.slice(0, 400)}; errors core ${inGame(c, "core", "no_errors").pass ? "none" : "SOME"}, play ${inGame(c, "play", "no_errors").pass ? "none" : "SOME"}`).join(" || ") };
    out.path_scratch_bounded = { pass: cfgs.every(c => inGame(c, "core", "path_scratch_bounded").pass), detail: cfgs.map(c => `${c}: ${inGame(c, "core", "path_scratch_bounded").detail.slice(0, 260)}`).join(" || ") };
    return out;
}

//-----------------------------------------------------------------------------
// Main

/** Run task functions (each returning a promise) at most JOBS at a time; resolves their results in order. */
const JOBS = Math.max(1, Number(arg("jobs", "3")) | 0);
async function pool(tasks) {
    const out = new Array(tasks.length);
    let next = 0;
    const worker = async () => { while (next < tasks.length) { const k = next++; out[k] = await tasks[k](); } };
    await Promise.all(Array.from({ length: Math.min(JOBS, tasks.length) }, worker));
    return out;
}
async function runAll(provocation) {
    const edits = provocation ? provocation.edits : null;
    const clone = provocation && provocation.clone ? provocation.clone : ROOT;
    const results = {};
    const phases = provocation && provocation.phases ? provocation.phases.filter(p => p !== "legacy") : ["core", "play", "sim"];
    const cfgs = provocation && provocation.configs ? provocation.configs.filter(c => CONFIGS.includes(c) || arg("z-range", "") === "") : CONFIGS;
    const tasks = [];
    // The longest runs first (sim), so the pool ends together.
    for (const ph of ["sim", "play", "core"].filter(p => phases.includes(p))) for (const c of cfgs) {
        (results[c] = results[c] || {});
        tasks.push(async () => { results[c][ph] = await runPhase(clone, `${provocation ? `p_${provocation.name}_` : ""}${c}_${ph}`, { ZR_PHASE: ph, DEUS_Z_RANGE: c }, edits); });
    }
    let save = null;
    if (!provocation || (provocation.phases || []).includes("legacy")) {
        const lf = legacyFiles();
        save = legacySaveFile();
        if (save) tasks.push(async () => { results.__legacy = await runPhase(clone, `${provocation ? `p_${provocation.name}_` : ""}legacy`, { ZR_PHASE: "legacy", DEUS_Z_RANGE: null, ZR_SAVE: save, ZR_FINGERPRINT: lf.fingerprint }, edits); });
    }
    await pool(tasks);
    if (save) fs.rmSync(save, { force: true });
    return results;
}
function loadBase() {
    const f = baseFixtureFile();
    return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, "utf8")) : null;
}

(async () => {
    try {
        if (flag("refresh-base")) { await refreshBase(); process.exit(0); }
        if (flag("make-legacy-fixture")) { await makeLegacyFixture(); process.exit(0); }
        if (arg("phase", "")) {
            const ph = arg("phase", ""), commit = arg("commit", "");
            const clone = commit ? require("./zrange/clone.js").makeClone(commit, `phase_${sha8(commit)}`).dir : ROOT;
            let save = null;
            const env = { ZR_PHASE: ph };
            if (ph === "legacy") { save = legacySaveFile(); Object.assign(env, { ZR_SAVE: save, ZR_FINGERPRINT: legacyFiles().fingerprint }); }
            const cfgs = ph === "legacy" || commit ? [null] : CONFIGS;
            const runs = await pool(cfgs.map(c => () => runPhase(clone, `${commit ? `c${sha8(commit)}_` : ""}${c || "own"}_${ph}`, Object.assign({}, env, { DEUS_Z_RANGE: c }))));
            for (const r of runs) {
                for (const line of r.text.split(/\r?\n/)) if (/^(PASS|FAIL|ERROR|HARNESS|RESULT)/.test(line)) log(line.slice(0, 2000));
                const out = path.join(os.tmpdir(), `laneaa_zr_phase_${ph}_${process.pid}_${runs.indexOf(r)}.json`);
                fs.writeFileSync(out, JSON.stringify(r.report, null, 1));
                log(`report: ${out}`);
            }
            if (save) fs.rmSync(save, { force: true });
            if (commit && !KEEP) require("./zrange/clone.js").removeTree(clone);
            process.exit(runs.every(r => r.result && /\(exit 0\)/.test(r.result)) ? 0 : 1);
        }
        const base = loadBase();
        if (!base) log(`NOTE: no base fixture ${baseFixtureFile()} (node tools/test_zrange.js --refresh-base makes it)`);
        const pv = arg("provoke", ""), all = flag("provoke-all");
        if (pv || all) {
            const names = all ? Object.keys(PROVOCATIONS) : pv.split(",");
            let uncaught = 0, broken = 0;
            for (const name of names) {
                const p = PROVOCATIONS[name];
                if (!p) { console.error(`unknown provocation ${name}; known: ${Object.keys(PROVOCATIONS).join(", ")}`); process.exit(2); }
                const prov = Object.assign({ name }, p);
                if (p.scanEdit) {
                    // The static scan runs on a copy of the plugins with the literal put back.
                    const tmp = path.join(os.tmpdir(), "laneaa_zr_scan", `${name}_${process.pid}`);
                    removeTree(tmp);
                    fs.mkdirSync(path.join(tmp, "game", "js"), { recursive: true });
                    fs.cpSync(path.join(ROOT, "game", "js", "plugins"), path.join(tmp, "game", "js", "plugins"), { recursive: true });
                    const [file, from, to] = p.scanEdit, fp = path.join(tmp, "game", "js", "plugins", file);
                    const src = fs.readFileSync(fp, "utf8").replace(/\r\n/g, "\n");
                    if (src.split(from).length !== 2) throw new Error(`scan edit target not exactly once in ${file}`);
                    fs.writeFileSync(fp, src.replace(from, () => to));
                    prov.scanRoot = tmp;
                }
                let r;
                try { r = await runAll(prov); } catch (e) { log(`PROVOCATION ${name}: HARNESS ${e.message}`); broken++; continue; }
                const ev = evaluate(r, p.withoutBase ? null : base, prov);
                const caught = ev[p.check] && !ev[p.check].pass;
                if (!caught) uncaught++;
                log(`${caught ? "CAUGHT" : "NOT CAUGHT"} provocation ${name} -> ${p.check}: ${ev[p.check] ? `${ev[p.check].pass ? "PASS" : "FAIL"} ${ev[p.check].detail.slice(0, 500)}` : "no result"}`);
                if (prov.scanRoot) removeTree(prov.scanRoot);
            }
            log(`PROVOCATIONS: ${names.length - uncaught - broken}/${names.length} caught${broken ? `, ${broken} harness problem(s)` : ""}`);
            process.exit(broken ? 2 : uncaught ? 1 : 0);
        }
        log(`=== WG.00.17 zrange: configurations ${CONFIGS.join(", ")}, seed ${SEED}, base ${sha8(BASE)}, ${UPDATES} updates, ${JOBS} run(s) at a time ===`);
        const results = await runAll(null);
        const ev = evaluate(results, base, null);
        let failed = 0;
        for (const name of CHECKS) {
            const c = ev[name];
            if (!c.pass) failed++;
            log(`${c.pass ? "PASS" : "FAIL"} ${name} - ${c.detail}`);
        }
        const harness = Object.values(results).some(r => r && (r.core ? ["core", "play", "sim"].some(ph => !r[ph] || !r[ph].result) : !r.result));
        const out = path.join(os.tmpdir(), `laneaa_zr_results_${process.pid}.json`);
        fs.writeFileSync(out, JSON.stringify({ configs: CONFIGS, seed: SEED, base: BASE, checks: ev, reports: Object.fromEntries(Object.entries(results).map(([k, v]) => [k, v.core ? { core: v.core.report, play: v.play && v.play.report, sim: v.sim && v.sim.report } : v.report])) }, null, 1));
        log(`reports: ${out}`);
        const code = failed ? 1 : harness ? 2 : 0;
        log(`RESULT: ${CHECKS.length - failed} passed, ${failed} failed (exit ${code})`);
        process.exit(code);
    } catch (e) {
        console.error(`HARNESS: ${e.stack || e.message}`);
        process.exit(2);
    }
})();
