// Makes a disposable copy of game/ for a test run and (optionally) runs a suite on it.
// The copy has its own js/, data/, index.html and package.json; img/, audio/ and the other asset folders are
// junctions to the real ones. So a run never touches the real plugins.js or test_output, and several runs
// can go at once (each gets its own browser profile from run_tests.js).
//
// Usage: node tools/test_snapshot.js [--name <n>] [--plugins A,B,C] [--suite <s>] [--dir <folder>] [--no-run]
//   --plugins  plugins to register in the copy's plugins.js, in this order, before UF_Test (which is added if missing)
//   --suite    suite name for run_tests.js (omit = default suites)
//   --dir      where to put the copy (default: %TEMP%\uf_snapshots\<name>)
//   --no-run   only make the copy (prints its path)
// Exit code: the run's exit code (0 passed, 1 failed, 2 harness problem), or 0 with --no-run.
"use strict";
const fs = require("fs");
const path = require("path");
const os = require("os");
const { spawnSync } = require("child_process");

const args = process.argv.slice(2);
const opt = (name, fallback) => {
    const i = args.indexOf(name);
    return i >= 0 && args[i + 1] !== undefined ? args[i + 1] : fallback;
};
const name = opt("--name", `run_${process.pid}`);
const plugins = (opt("--plugins", "") || "").split(",").map(s => s.trim()).filter(Boolean);
const suite = opt("--suite", null);
const root = path.resolve(__dirname, "..");
const game = path.join(root, "game");
const dir = path.resolve(opt("--dir", path.join(os.tmpdir(), "uf_snapshots", name)));
const noRun = args.includes("--no-run");

// A fresh copy every time: old snapshots with stale plugins have caused false failures.
if (fs.existsSync(dir)) {
    // Junctions must go with rmSync's junction-aware unlink; deleting through them would empty the real folders.
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, entry.name);
        if (entry.isSymbolicLink() || (fs.lstatSync(p).isSymbolicLink())) fs.unlinkSync(p);
        else fs.rmSync(p, { recursive: true, force: true });
    }
} else {
    fs.mkdirSync(dir, { recursive: true });
}

const COPY = ["js", "data", "index.html", "package.json"];
for (const entry of fs.readdirSync(game, { withFileTypes: true })) {
    const src = path.join(game, entry.name), dst = path.join(dir, entry.name);
    if (["test_output", "save", "game_runtime.log", "test_screenshot.png"].includes(entry.name)) continue;
    if (COPY.includes(entry.name)) {
        fs.cpSync(src, dst, { recursive: true });
    } else if (entry.isDirectory()) {
        fs.symlinkSync(src, dst, "junction");
    } else {
        fs.copyFileSync(src, dst);
    }
}
fs.mkdirSync(path.join(dir, "test_output"), { recursive: true });

// Register plugins: keep the real order, insert the requested ones before UF_Test, add UF_Test last if missing.
const pluginsFile = path.join(dir, "js", "plugins.js");
const text = fs.readFileSync(pluginsFile, "utf8").replace(/^﻿/, "");
const list = JSON.parse(text.slice(text.indexOf("["), text.lastIndexOf("]") + 1));
const without = list.filter(p => p.name !== "UF_Test");
for (const p of plugins) {
    if (!without.some(q => q.name === p)) without.push({ name: p, status: true, description: `[${p}]`, parameters: {} });
}
const test = list.find(p => p.name === "UF_Test") || { name: "UF_Test", status: true, description: "[UF_Test]", parameters: {} };
test.status = true;
without.push(test);
fs.writeFileSync(pluginsFile, `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${without.map(p => JSON.stringify(p)).join(",\n")}\n];\n`);
const missing = without.filter(p => !fs.existsSync(path.join(dir, "js", "plugins", `${p.name}.js`))).map(p => p.name);
console.log(`snapshot: ${dir}`);
console.log(`plugins: ${without.map(p => p.name).join(" > ")}`);
if (missing.length) console.log(`WARNING: registered but no file: ${missing.join(", ")}`);
if (noRun) process.exit(0);

const runArgs = [path.join(__dirname, "run_tests.js")];
if (suite) runArgs.push(suite);
runArgs.push("--game", dir);
const r = spawnSync(process.execPath, runArgs, { stdio: "inherit" });
console.log(`results: ${path.join(dir, "test_output", "results.txt")}; screenshots in ${path.join(dir, "test_output")}`);
process.exit(r.status === null ? 2 : r.status);
