// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
  {
    "name": "DEUS_Core",
    "status": true,
    "description": "[DEUS Core] Foundation systems: shared state, time domains, deterministic RNG, coordinate math, spatial queries, and engine hooks.",
    "parameters": {
      "TimeSpeed": "1.0",
      "StartHour": "8",
      "StartMinute": "0",
      "ShowClockHUD": "false"
    }
  },
  {
    "name": "DEUS_Visuals",
    "status": true,
    "description": "[DEUS Visuals] Visual pipeline: high-DPI scaling, viewport rendering, 2.5D projection, and pixel-crisp display.",
    "parameters": {
      "EnableRoofs": "true",
      "EnableBarks": "true",
      "EnableLighting": "false"
    }
  },
  {
    "name": "DEUS_Movement8D",
    "status": true,
    "description": "[DEUS Movement8D] 8-directional movement, Octile A* pathfinding, strict corner collision, and diagonal navigation.",
    "parameters": {
      "NormalizeSpeed": "true",
      "StrictCornerCutting": "true",
      "DiagonalSlide": "true"
    }
  },
  {
    "name": "DEUS_Perspective25D",
    "status": true,
    "description": "[DEUS Perspective25D] 2.5D elevation layers, dynamic Z-depth sorting, real-time directional cast shadows, and canopy occlusion.",
    "parameters": {
      "TileHeightStep": "36",
      "EnableShadows": "true",
      "OcclusionOpacity": "120"
    }
  },
  {
    "name": "DEUS_ColonyOverseer",
    "status": true,
    "description": "[DEUS ColonyOverseer] Real-time colony simulation, unit selection cards, order issuance, designation markers, and speed controls.",
    "parameters": {
      "EdgePanSpeed": "6"
    }
  },
  {
    "name": "DEUS_World",
    "status": true,
    "description": "[DEUS World] Seeded multi-level procedural world generation, persistent area maps, coordinate translation, and world state.",
    "parameters": {}
  },
  {
    "name": "DEUS_WorldGen",
    "status": true,
    "description": "[DEUS WorldGen] Multi-octave Perlin terrain synthesis, elevation and moisture maps, geological strata, and biome placement.",
    "parameters": {}
  },
  {
    "name": "DEUS_Tiles",
    "status": true,
    "description": "[DEUS Tiles] Dynamic terrain autotiling, biome transitions, elevation cliffs, and multi-layer autotile rendering.",
    "parameters": {}
  },
  {
    "name": "DEUS_Factions",
    "status": true,
    "description": "[DEUS Factions] 11 cultural factions, cultural identities, diplomatic relations, and stance matrices.",
    "parameters": {}
  },
  {
    "name": "DEUS_History",
    "status": true,
    "description": "[DEUS History] World history generation, settlement founding, faction site placement, founder genealogies, and historical events.",
    "parameters": {}
  },
  {
    "name": "DEUS_Objects",
    "status": true,
    "description": "[DEUS Objects] Catalog-driven world objects, multi-state interaction cycles (intact/ruined/harvested), and spatial placement.",
    "parameters": {}
  },
  {
    "name": "DEUS_Walls",
    "status": true,
    "description": "[DEUS Walls] Structural 2-tile wall systems with black wall-top occlusion convention, material durability, and construction.",
    "parameters": {}
  },
  {
    "name": "DEUS_Doors",
    "status": true,
    "description": "[DEUS Doors] Cultural architectural doors, faction-aware access control, open/closed animation states, and durability.",
    "parameters": {}
  },
  {
    "name": "DEUS_Items",
    "status": true,
    "description": "[DEUS Items] Ground item entities, inventory stacks, material properties, decay rates, and container storage.",
    "parameters": {}
  },
  {
    "name": "DEUS_Jobs",
    "status": true,
    "description": "[DEUS Jobs] Autonomous colony job dispatch, work reservations, tool efficiency scaling, and task execution.",
    "parameters": {}
  },
  {
    "name": "DEUS_Floors",
    "status": true,
    "description": "[DEUS Floors] Room enclosure detection, cultural flooring construction, floor autotiles, and architectural room value.",
    "parameters": {}
  },
  {
    "name": "DEUS_Generator",
    "status": true,
    "description": "[DEUS Generator] Procedural composite character sprite assembly, portrait generation, and demographic variation.",
    "parameters": {}
  },
  {
    "name": "DEUS_Colonists",
    "status": true,
    "description": "[DEUS Colonists] Colony population manager, autonomous AI schedules, society planning, and colonist equipment priorities.",
    "parameters": {}
  },
  {
    "name": "DEUS_Projects",
    "status": true,
    "description": "[DEUS Projects] Authoritative settlement-level construction planner: deficit detection, phased blueprints, site selection, and physical build orders.",
    "parameters": {}
  },
  {
    "name": "DEUS_Wildlife",
    "status": true,
    "description": "[DEUS Wildlife] Wild fauna populations, grazing herds, predator/prey behaviors, sensory awareness, and flee AI.",
    "parameters": {}
  },
  {
    "name": "DEUS_Ecology",
    "status": true,
    "description": "[DEUS Ecology] Environmental regrowth systems: plant spreading, flora regeneration, and sustainable wildlife repopulation.",
    "parameters": {}
  },
  {
    "name": "DEUS_Stance",
    "status": true,
    "description": "[DEUS Stance] Diplomatic stance indicators: colored selection rings reflecting unit disposition (friendly, neutral, hostile).",
    "parameters": {}
  },
  {
    "name": "DEUS_Combat",
    "status": true,
    "description": "[DEUS Combat] Real-time tick-based combat: SRD 5.1 attack/defense rolls, hit resolution, damage splats, and health bars.",
    "parameters": {}
  },
  {
    "name": "DEUS_Anim",
    "status": true,
    "description": "[DEUS Anim] Sprite-driven animation engine for 12-sprite character sets, directional action cycles, and object states.",
    "parameters": {}
  },
  {
    "name": "DEUS_Fog",
    "status": true,
    "description": "[DEUS Fog] Fog of war occlusion, line-of-sight revelation, faction vision sharing, and persistent exploration memory.",
    "parameters": {}
  },
  {
    "name": "DEUS_DayNight",
    "status": true,
    "description": "[DEUS DayNight] Celestial day/night cycle, dynamic ambient lighting, solar shadows, underground illumination, and clock HUD.",
    "parameters": {
      "NightVision": "0.55",
      "ShowClock": "false"
    }
  },
  {
    "name": "DEUS_TimeSpeed",
    "status": true,
    "description": "[DEUS TimeSpeed] Simulation speed controller (1x, 2x, 4x, 8x, 16x, 32x), active world pause, and game-time scheduling.",
    "parameters": {
      "Speeds": "1, 2, 4, 8"
    }
  },
  {
    "name": "DEUS_Camera",
    "status": true,
    "description": "[DEUS Camera] Pixel-exact camera zoom controls, smooth panning navigation, and entity target tracking.",
    "parameters": {}
  },
  {
    "name": "DEUS_Culling",
    "status": true,
    "description": "[DEUS Culling] Viewport and presentation culling engine: spatial bucket indexing, offscreen sprite parking, and 60 FPS viewport dispatch.",
    "parameters": {}
  },
  {
    "name": "DEUS_Speech",
    "status": true,
    "description": "[DEUS Speech] Floating overhead dialogue balloons, situational barks, emotional remarks, and colony announcements.",
    "parameters": {}
  },
  {
    "name": "DEUS_Look",
    "status": true,
    "description": "[DEUS Look] Cursor inspection tooltip: cell terrain, biome properties, occupants, objects, and asset provenance.",
    "parameters": {}
  },
  {
    "name": "DEUS_Interact",
    "status": true,
    "description": "[DEUS Interact] Contextual right-click interaction menu, order designation markers, and immediate job creation.",
    "parameters": {}
  },
  {
    "name": "DEUS_Sheet",
    "status": true,
    "description": "[DEUS Sheet] Entity inspection panel: 14-slot equipment paperdoll, inventory grid, attributes, and object contents.",
    "parameters": {}
  },
  {
    "name": "DEUS_Talk",
    "status": true,
    "description": "[DEUS Talk] Modal conversation interface: faction portraits, branching dialogue keywords, and lore exchange.",
    "parameters": {}
  },
  {
    "name": "DEUS_Fire",
    "status": true,
    "description": "[DEUS Fire] Cellular fire propagation, material flammability, burn damage, firefighter water bucket jobs, and burnout.",
    "parameters": {}
  },
  {
    "name": "DEUS_Levels",
    "status": true,
    "description": "[DEUS Levels] Multi-level vertical world: 5 persistent elevation layers (-2 to +2), caverns, and Z-level transitions.",
    "parameters": {}
  },
  {
    "name": "DEUS_Ownership",
    "status": true,
    "description": "[DEUS Ownership] Entity property ownership, personal bed claims, private quarters designation, and sleep allocation.",
    "parameters": {}
  },
  {
    "name": "DEUS_Environment",
    "status": true,
    "description": "[DEUS Environment] Environmental simulation: ambient temperature, body regulation, shelter insulation, and weather effects.",
    "parameters": {}
  },
  {
    "name": "DEUS_NaturalConnections",
    "status": true,
    "description": "[DEUS NaturalConnections] Natural cavern passages, vertical stairwells, and physical traversal between surface and underground.",
    "parameters": {}
  },
  {
    "name": "DEUS_FactionMenus",
    "status": true,
    "description": "[DEUS FactionMenus] Dynamic cultural UI themes, window skins, Title Screen embark setup, and custom faction mouse cursors.",
    "parameters": {}
  },
  {
    "name": "DEUS_Depth",
    "status": true,
    "description": "[DEUS Depth] Crisp depth projection of the levels below the viewed level, seen through open air (owner direction 2026-09-24).",
    "parameters": {
      "MaxDepth": "2"
    }
  },
  {
    "name": "DEUS_Test",
    "status": true,
    "description": "[DEUS Test] Automated test harness: PASS/FAIL test suites, screenshot verification, and performance benchmarks.",
    "parameters": {}
  }
];
