// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"UF_BootstrapData","status":true,"description":"Bootstrap container inventories","parameters":{}},
{"name":"UF_Core","status":true,"description":"[UF Core] 24-hour clockwork time simulation, calendar, and world state for Ultima Fortress.","parameters":{"TimeSpeed":"1.0","StartHour":"8","StartMinute":"0","ShowClockHUD":"true"}},
{"name":"UF_Visuals","status":true,"description":"[UF Visuals] Roof cutaways, overhead floating speech barks, and 24-hour day/night atmospheric lighting.","parameters":{"EnableRoofs":"true","EnableBarks":"true","EnableLighting":"true"}},
{"name":"UF_Gumps","status":true,"description":"[UF Gumps] Draggable container gumps (chests, barrels, sacks) and classic U7 paperdoll equipment interface.","parameters":{"EnableGumps":"true","EnablePaperdoll":"true"}},
{"name":"UF_NPCSchedules","status":true,"description":"[UF Schedules] 24-hour autonomous routines for fortress NPCs (workshops, tavern, dining hall, sleeping in beds).","parameters":{}},
{"name":"UF_Dialogue","status":true,"description":"[UF Dialogue] Classic Ultima VII keyword conversation trees with character portraits and party interjections.","parameters":{}},
{"name":"UF_DFWorld","status":true,"description":"[UF DFWorld] Authentic Dwarf Fortress naming generator, personality traits, preferences, and Strange Mood artifact crafting.","parameters":{}},
{"name":"UF_DFCombat","status":true,"description":"[UF DFCombat] Dwarf Fortress anatomical wound simulation (body parts, tissues, severed limbs, bleeding, and authentic DF combat announcements).","parameters":{}},
{"name":"UF_Crafting","status":true,"description":"[UF Crafting] Dwarf Fortress workshop reactions and Precursor fabrication.","parameters":{}},
{"name":"UF_Movement8D","status":true,"description":"[UF Movement8D] True 8-directional grid movement, octile A* pathfinding, and corner-cutting collision control.","parameters":{"NormalizeSpeed":"true","StrictCornerCutting":"true","DiagonalSlide":"true"}},
{"name":"UF_Perspective25D","status":true,"description":"[UF Perspective25D] Ultima VII 2.5D axonometric projection, Z-elevation, dynamic depth sorting, canopy occlusion, and cast shadows.","parameters":{"TileHeightStep":"36","EnableShadows":"true","OcclusionOpacity":"120"}},
{"name":"UF_ColonyOverseer","status":true,"description":"[UF ColonyOverseer] DF-style free overseer camera, tactile unit selection, colonist status card, and autonomous biological needs.","parameters":{"EdgePanSpeed":"6"}},
{"name":"UF_Construction","status":true,"description":"[UF Construction] Dwarf Fortress grid-based blueprint construction, natural resource gathering, and hauling jobs.","parameters":{}},
{"name":"UF_ProcGen","status":true,"description":"[UF ProcGen] Standardized Edenic Glade embark (Fruit tree, Stream, Adam & Eve) and procedural DF wilderness generation.","parameters":{"GladeRadius":"12"}}
];

