#!/usr/bin/env node
"use strict";
// SIM.00.00 (Lane N): runs existing UF_Test suites on main and on the lane tip with the same world seed, so a check that
// differs between the two is the lane's doing, not another world. Each side gets its own snapshot of game/ (robocopy to
// %TEMP%); for main, every file under game/ that differs from main is replaced by main's version. Nothing under game/ is
// written. Output: one results file per side and suite in tasks/SIM.00.00/lane-n/suites/, and a summary on stdout.
// Usage: node tasks/SIM.00.00/lane-n/run_existing_suites.js [--seed=18] [--sides=main,tip] [suite ...]
// Exit: 0 no check differs between the sides, 1 a check differs (or a side's run broke), 2 harness problem.

const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync, execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..", "..", "..");
const OUT = path.join(__dirname, "suites");
const arg = (name, fallback) => {
    const a = process.argv.find(x => x.startsWith(`--${name}=`));
    return a ? a.slice(name.length + 3) : fallback;
};
const seed = Number(arg("seed", "18"));
const sides = arg("sides", "main,tip").split(",");
const suites = process.argv.slice(2).filter(a => !a.startsWith("--"));
const SUITES = suites.length ? suites : ["vertical", "world", "spawn", "natural_walls", "flooding", "strata"];

function snapshot(side) {
    const dir = path.join(os.tmpdir(), "deus_lane_n_suites", `${side}_${process.pid}`);
    fs.rmSync(dir, { recursive: true, force: true });
    fs.mkdirSync(dir, { recursive: true });
    const rc = spawnSync("robocopy", [path.join(ROOT, "game"), dir, "/E", "/NDL", "/NFL", "/NJH", "/NJS", "/NC", "/NS", "/NP", "/XD", "test_output", "save"], { stdio: "ignore" });
    if (rc.status === null || rc.status >= 8) throw new Error(`robocopy failed (${rc.status})`);
    let taken = [];
    if (side !== "tip") {
        taken = execFileSync("git", ["-C", ROOT, "diff", "--name-only", side, "--", "game"], { encoding: "utf8" }).split(/\r?\n/).filter(Boolean);
        for (const name of taken) {
            const dst = path.join(dir, name.replace(/^game\//, ""));
            let body = null;
            try { body = execFileSync("git", ["-C", ROOT, "show", `${side}:${name}`], { maxBuffer: 256 * 1024 * 1024 }); } catch (_) { body = null; }
            if (body === null) fs.rmSync(dst, { force: true });
            else fs.writeFileSync(dst, body);
        }
    }
    const pj = path.join(dir, "js", "plugins.js");
    const text = fs.readFileSync(pj, "utf8").replace(/^﻿/, "");
    const plugins = JSON.parse(text.slice(text.indexOf("["), text.lastIndexOf("]") + 1));
    const world = plugins.find(p => p.name === "DEUS_World");
    world.parameters = Object.assign({}, world.parameters, { Seed: String(seed) });
    fs.writeFileSync(pj, `// Generated by RPG Maker.\n// Do not edit this file directly.\nvar $plugins =\n[\n${plugins.map(p => JSON.stringify(p)).join(",\n")}\n];\n`);
    return { dir, taken };
}

function run(dir, suite) {
    const r = spawnSync(process.execPath, [path.join(ROOT, "tools", "run_tests.js"), suite, "--game", dir], { encoding: "utf8", timeout: 400000 });
    const file = path.join(dir, "test_output", "results.txt");
    const text = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : `(no results file; run_tests exit ${r.status})\n${r.stdout || ""}${r.stderr || ""}`;
    const checks = {};
    for (const line of text.split(/\r?\n/)) {
        const m = line.match(/^(PASS|FAIL) ([\w.]+)/);
        if (m) checks[m[2]] = m[1];
    }
    return { status: r.status, text, checks, result: (text.match(/^RESULT: .*$/m) || ["(no RESULT line)"])[0] };
}

fs.mkdirSync(OUT, { recursive: true });
const results = {};
// --compare: no runs; read the results files saved by earlier runs (one side and batch of suites at a time).
const parse = text => {
    const checks = {};
    for (const line of text.split(/\r?\n/)) {
        const m = line.match(/^(PASS|FAIL) ([\w.]+)/);
        if (m) checks[m[2]] = m[1];
    }
    return { text, checks, result: (text.match(/^RESULT: .*$/m) || ["(no RESULT line)"])[0] };
};
if (process.argv.includes("--compare")) {
    for (const side of sides) {
        results[side] = {};
        for (const suite of SUITES) {
            const f = path.join(OUT, `${side}_${suite}.txt`);
            results[side][suite] = parse(fs.existsSync(f) ? fs.readFileSync(f, "utf8") : "");
            console.log(`${side} ${suite}: ${results[side][suite].result}`);
        }
    }
}
for (const side of process.argv.includes("--compare") ? [] : sides) {
    const { dir, taken } = snapshot(side);
    console.log(`${side}: snapshot ${dir}${taken.length ? ` (from ${side}: ${taken.join(", ")})` : ""}, seed ${seed}`);
    results[side] = {};
    for (const suite of SUITES) {
        const t0 = Date.now();
        const r = run(dir, suite);
        results[side][suite] = r;
        fs.writeFileSync(path.join(OUT, `${side}_${suite}.txt`), r.text);
        console.log(`  ${suite}: exit ${r.status}, ${r.result} (${((Date.now() - t0) / 1000).toFixed(0)} s)`);
    }
    fs.rmSync(dir, { recursive: true, force: true });
}

let differ = 0;
if (sides.length === 2) {
    const [a, b] = sides;
    console.log(`\nChecks that differ between ${a} and ${b}:`);
    for (const suite of SUITES) {
        const ca = results[a][suite].checks, cb = results[b][suite].checks;
        for (const name of Array.from(new Set([...Object.keys(ca), ...Object.keys(cb)])).sort()) {
            if (ca[name] === cb[name]) continue;
            differ++;
            console.log(`  ${name}: ${a} ${ca[name] || "NOT RUN"}, ${b} ${cb[name] || "NOT RUN"}`);
        }
    }
    if (!differ) console.log("  none");
}
process.exit(differ ? 1 : 0);
